### ISSUE TITLE
Which service should port 11223 be bound to the swarm environment?

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato#1029]
zato_bootstrap or zato_scheduler or zato_server or zato_webadmin?
By the way, what role does zato_bootstrap,i can't find the port configuration of the zato_bootstrap in docker-compose.yml, I go to 8183, the system says: "Could not fetch the load balancer's configuration", the others are normal
 thank you!
![zato](https://user-images.githubusercontent.com/9400678/76083179-f32b3280-5fe7-11ea-8463-adacdb6b7ffd.png)

**Comment by DimShadoWWW** [comment]
In Docker Swarm this screen has no function for now.

In the template for Docker Swarm:
- The role of **zato_bootstrap** is to initialize the cluster in the ODB: "create odb" and "create cluster"
- We use **traefik** (container named **zato_lb** ) as load balancer in Docker Swarm to Zato server component instances. It can communicate to Docker directly and get the information of every instance.

**Comment by aixi88** [comment]
thank you!
It's finally ready to use
![zato](https://user-images.githubusercontent.com/9400678/76136367-a1c48700-606b-11ea-9c1f-f04f18ed1206.png)
