### ISSUE TITLE
I can't upload a service code that contains sqlalchemy class, what should I do?

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato#1032]
The following code changes Base  to object that can be uploaded，why?
thanks!

from sqlalchemy import Numeric, String, Column
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
from zato.server.service import Service

class so_dispatchlist(Base):

    __tablename__ = 'so_dispatchlist'

    ccode = Column(String(200), unique=True, nullable=False)
    ccuscode = Column(String(200), nullable=False)
    cinvcode = Column(String(1000), nullable=True)
    fh_iquantity = Column(Numeric(), nullable=False)

class CustomerConsignmentService(Service):
       class SimpleIO:
            input_required = ('ccuscode')
             output_required = ('ccode', 'so_dispatchlist_list')

    def handle(self):
        pass

**Comment by dsuch** [comment]
Hello @aixi88,

I have no idea what you mean, what you are trying to do, what works, what does not work and what you expect for the end result to be.

Your code cannot be read because it not formatted at all.

I am closing this ticket - feel free reopen after rectifying these matters.

Regards.

**Comment by aixi88** [comment]
sorry ,My English is not good, so the expression is not very clear, the following code upload can not be found in the service, unless you change the class so_dispatchlist (Base) to class so_dispatchlist (object)

```
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
from zato.server.service import Service

class so_dispatchlist(Base):

    __tablename__ = 'so_dispatchlist'

    ccode = Column(String(200), unique=True, nullable=False)
    ccuscode = Column(String(200), nullable=False)
    cinvcode = Column(String(1000), nullable=True)
    fh_iquantity = Column(Numeric(), nullable=False)

class CustomerConsignmentService(Service):
    class SimpleIO:
        input_required = ('ccuscode')
        output_required = ('ccode', 'so_dispatchlist_list')

    def handle(self):
        pass
```

**Comment by dsuch** [comment]
Ok, but I do not understand what does not work exactly, what do you mean by "cannot be found"?

This is an SQLAlchemy class, not a Zato one, and I do not know how they work like exactly.

**Comment by aixi88** [comment]
cannot be found on : http:// 8183/zato/service/?cluster=1 ,after  upload services
![zato](https://user-images.githubusercontent.com/9400678/76685922-55241180-6652-11ea-80f1-e98284ce27ec.png)

**Comment by dsuch** [comment]
Do you know that there is a file called server.log which contains various details, including exceptions or errors?

**Comment by aixi88** [comment]
@dsuch i dont know.I'm using Docker swarm

**Comment by dsuch** [comment]
I see - let me explain. A file called server.log is one of the log files that exist for each server. This one is the main one where you will likely find an explanation, a Python traceback, with details that prevent Zato from deploying your service.

You need to somehow SSH into your server and find the file. I am not really familiar with Docker so I do not know how to use SSH with Swarm.

**Comment by aixi88** [comment]
@dsuch 
I found out why, because there was no primary_key,thank you!
```
class so_dispatchlist(Base):

    __tablename__ = 'so_dispatchlist'

    ccode = Column(String(200), primary_key=True)
    ccuscode = Column(String(200), nullable=False)
    cinvcode = Column(String(1000), nullable=True)
    fh_iquantity = Column(Numeric(), nullable=False)
```

**Comment by dsuch** [comment]
OK, this is good to hear.
