### ISSUE TITLE
Directory /opt/zato/env/qs-1 is not empty, please re-run the command in an empty directory

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato#1035]
mes_zato_bootstrap.1.lwbx5yl0a3qy@mes    | /opt/zato/current/bin/zato create load_balancer  --verbose  /opt/zato/env/qs-1/
mes_zato_bootstrap.1.lwbx5yl0a3qy@mes    | 2020-04-11 04:17:36,829 - INFO - 208:MainThread - Create:624 - Directory /opt/zato/env/qs-1 is not empty, please re-run the command in an empty directory
mes_zato_bootstrap.1.lwbx5yl0a3qy@mes    | Directory /opt/zato/env/qs-1 is not empty, please re-run the command in an empty directory

Can the system allow the use of non-empty directories?
thanks!

**Comment by dsuch** [comment]
Hello @aixi88,

no, this is explicitly disallowed in order to rule out any potential issues stemming from users not being sure what is empty and what is not.

If your question is in the context of scripting then please empty out such directories yourself in your scripts.

Regards.

**Comment by aixi88** [comment]
Okay, thank you, I'll look again.

**Comment by dsuch** [comment]
Great, I am closing the ticket in this case. Thanks.
