### ISSUE TITLE
Returning User Friendly SIO validation errors

### ISSUE THREAD

**Issue by Xorso** [zatosource/zato#1040]
Is it possible to return a better validation error message (and not a 500 either) when an external request makes a REST request to a service that fails SIO validation?

Currently the output is the Traceback of the failure (because of a ValidationException being raised, also, ParsingException applies as well if they miss a required field).

It has made it difficult to point our customers to the errors message to find the fields they are missing to submit.

**Comment by dsuch** [comment]
Hello @Xorso,

if this is about a commercial usage of Zato then the public GitHub tracker is not a good place to discuss it.

Please contact me on dsuch at zato.io instead.

Thank you.

**Comment by dsuch** [comment]
Closing old tickets.
