### ISSUE TITLE
Problems with Chinese characters in service code

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato#1044]
If there is Chinese in the service code, it cannot be uploaded, and there are Chinese comments that cannot be。
I've added “# -*- coding: utf-8 -*-”

thanks!

**Comment by dsuch** [comment]
Hi @aixi88,

please read this article:

https://opensource.com/life/16/10/how-ask-technical-questions

I am closing this ticket. Please free to re-open, or to create new ones, once you can follow the recommendations from the article.

Otherwise, it is impossible for us to assist you.

Regards.
