### ISSUE TITLE
Public Key not importable

### ISSUE THREAD

**Issue by samyn92** [zatosource/zato#1058]
Hi,

today i was trying to install Zato 3.1. (Ubuntu), but i got an error importing the public key:

$ curl -s https://zato.io/repo/zato-3.1-C9B13DF28CFE3.xD.pgp.txt | sudo apt-key add -
gpg: no valid OpenPGP data found.

**Comment by dsuch** [comment]
Hello @samyn92 - you were trying to install Zato using what Ubuntu version exactly?

**Comment by samyn92** [comment]
Hi @dsuch,

I'm using Ubuntu 18.04.4 LTS

**Comment by dsuch** [comment]
Where did you get the URL for the PGP key from? It is invalid.

**Comment by samyn92** [comment]
It's from this Guide:

https://zato.io/docs/3.1/admin/guide/install/py3/ubuntu.html

"Add the package signing key
ubuntu$ curl -s https://zato.io/repo/zato-3.1-C9B13DF28CFE3.xD.pgp.txt | sudo apt-key add -"

**Comment by dsuch** [comment]
I see, that was a typo, thanks for reporting it. Can you try it out now?

**Comment by dsuch** [comment]
I assume that it works and I am closing the ticket.

@samyn92 - in the future, please confirm the outcome of such changes.
