### ISSUE TITLE
FTP issue with dircache

### ISSUE THREAD

**Issue by DickKnol** [zatosource/zato#1059]
On Zato 3.1, probably due to upgrade of pyfilesystem, it is not connecting anymore as the FTPFS constructor has different parameters now (dircache is sent as proxy).

Although I cannot find the dependency on the fs package anymore, pyfilesytem 2.2.1 is installed and used on Ubuntu 18.04

Furthermore, the new version is API incompatible, making the documention invalid.

**Comment by dsuch** [comment]
I am working on it now - can you send me your code and any exceptions that you are receiving? I would like to confirm that we are discussing the same thing. Thanks.

**Comment by dsuch** [comment]
By the way, regarding the dependencies.

The ones that are common to Python 2 and 3 are in requirements.txt. But some differ between the two Python versions.

They are in _req_py27.txt and _req_py3.txt, respectively.

**Comment by dsuch** [comment]
This is done - please install the latest updates and try it out:

https://zato.io/docs/admin/guide/install/update.html
