### ISSUE TITLE
I think, this line must be like a line #83

### ISSUE THREAD

**Issue by OstapYakovenko** [zatosource/zato#1072]
https://github.com/zatosource/zato/blob/0789927242e6504871065a7ddb2e1b3143c71b7b/code/zato-server/src/zato/server/service/internal/outgoing/sql.py#L138

**Comment by dsuch** [comment]
Thanks, you are right - would you please send in a PR? I will be happy to accept it.

**Comment by dsuch** [comment]
Done.
