### ISSUE TITLE
UnicodeEncodeError: 'ascii'

### ISSUE THREAD

**Issue by efgieha** [zatosource/zato#1073]
https://github.com/zatosource/zato/blob/e23dac04e872b676935f393e62216f06f6314c52/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py#L154

If you have e.g. polish characters like "ł, ó", hot deploy raise UnicodeEncodeError. I change this line to:
```f = open(file_name, "w", encoding="utf-8")```
and it works properly

**Comment by DimShadoWWW** [comment]
Hello @efgieha ,
Please, can you can pull the latest updates and check again? https://zato.io/docs/admin/guide/install/update.html

Thank you

**Comment by efgieha** [comment]
It works. Thanks a lot. :)
