### ISSUE TITLE
debian apt install broken

### ISSUE THREAD

**Issue by petri** [zatosource/zato#1080]
Following the instructions, after adding zato as apt source and trying apt-get update:

E: The repository 'https://zato.io/repo/stable/3.1/py3/debian $(lsb_release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Here's the actual apt source line:

`deb [arch=amd64] https://zato.io/repo/stable/3.1/py3/debian buster main`

Also, the install on debian should not perhaps specify `add-apt-repository` command as the way to add the zato repo apt source: It is not installed by default on buster and adds a lot of unnecessary package dependencies.

**Comment by dsuch** [comment]
Hello @petri,

Debian Buster was released some time after Zato 3.1 was released and there is no package for it yet. Zato 3.2 will be released in December and this version will ship with a package for Buster.

In the meantime, please install Zato from source or use a different OS version.

https://zato.io/docs/admin/guide/install/py3/source.html

Here is the list of all the operating systems that we have packages for:

https://zato.io/docs/admin/guide/install/index.html

A binary package installer, a .deb or an .rpm is not much different than installation from source, it just wraps everything under a single package.

Thanks.

**Comment by petri** [comment]
Oh I did not realize there was no buster support. Thanks.

**Comment by dsuch** [comment]
The system is supported even if there is no binary .deb installer - you can install Zato from source and you will achieve exactly the same result as if you installed it from a .deb package.

**Comment by dsuch** [comment]
Just a quick update - in addition to a source installation, we have already prepared .deb packages for Debian 10 for the upcoming Zato 3.2 release. They will be part of the upcoming Zato 3.2 release. https://travis-ci.org/github/zatosource/zato-build/builds/738820959
