### ISSUE TITLE
Error: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by mhdaouas** [zatosource/zato#1094]
When I try to pull/run the Quickstart image with the following commands:

`sudo docker pull registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3`

or

`sudo docker run -it --rm -p 22 -p 6379:6379 -p 8183:8183 -p 17010:17010 -p 17011:17011         -p 11223:11223 --name zato         registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3`

I get the following error:

> Error response from daemon: Get https://registry.gitlab.com/v2/zatosource/docker-registry/quickstart/manifests/3.1: Get https://gitlab.com/jwt/auth?scope=repository%3Azatosource%2Fdocker-registry%2Fquickstart%3Apull&service=container_registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

It seems like I need to login but no credentials are mentioned in the official tutorial available at the following link:
https://zato.io/docs/admin/guide/install/py3/docker.html

Some people also mention that you need to add the following lines to the file /etc/resolve.conf:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

or setup the proxy manually (if you're behind a proxy) for Docker in` /etc/systemd/system/docker.service.d` with the following lines:

```
[Service]
Environment="HTTP_PROXY=http://USER:PASSWD@SERVER:PORT/"
Environment="HTTPS_PROXY=http://USER:PASSWD@SERVER:PORT/"
```

and then restarting Docker services:
```
systemctl daemon-reload
systemctl restart docker
```

Both solutions didn't work for me.

I even tried different versions of the quickstart image/Python without success.

My configuration:

Centos 8

**Comment by dsuch** [comment]
Hello @mhdaouas,

a colleague of mine will respond regarding Docker but I just wanted to mention that the details of how to obtain credentials are at the link here https://zato.io/docs/admin/guide/install/py3/docker.html.

Specifically, in the "Retrieve your dynamically generated passwords." bullet of the "Quickstart cluster" section - can you check again, please?

There are never any hardcoded or default secrets for anything in Zato - everything is always auto-generated for each environment separately.

Regards.

**Comment by mhdaouas** [comment]
Thanks dsuch for your quick response. What I mean by missing credentials, are credentials for pulling/initial running of the Zato Quickstart Docker container, not the credentials that you need after creating the container to access the admin web interface which you mentioned.

**Comment by dsuch** [comment]
@DimShadoWWW is the author and he will reply too later on but I think there is nothing special required in terms of credentials - if you run the command with sudo then this is all that matters, that your user can execute sudo commands.

But let's wait for @DimShadoWWW to confirm it.

**Comment by DimShadoWWW** [comment]
Hello @mhdaouas ,

The Docker Registry is public and you should be able to pull the image from it.

This error main cause of this error is when your Docker can not connect to the Registry.

Please, can you check if your system can resolve the hostname when it fails to pull the image? e.g. : `curl -v https://registry.gitlab.com`

thanks,

**Comment by mhdaouas** [comment]
Thanks for your support DimShadoWWW. Here is the output of the curl command:

> * Rebuilt URL to: https://registry.gitlab.com/
> *   Trying 35.227.35.254...
> * TCP_NODELAY set
> * Connected to registry.gitlab.com (35.227.35.254) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>   CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: CN=registry.gitlab.com
> *  start date: Mar 24 00:00:00 2020 GMT
> *  expire date: May 22 23:59:59 2021 GMT
> *  subjectAltName: host "registry.gitlab.com" matched cert's "registry.gitlab.com"
> *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
> *  SSL certificate verify ok.
> > GET / HTTP/1.1
> > Host: registry.gitlab.com
> > User-Agent: curl/7.61.1
> > Accept: */*
> >
> < HTTP/1.1 200 OK
> < Cache-Control: no-cache
> < Date: Wed, 11 Nov 2020 07:45:03 GMT
> < Content-Length: 0
> <
> * Connection #0 to host registry.gitlab.com left intact
>

**Comment by DimShadoWWW** [comment]
hello @mhdaouas ,

Please, can you try to pull the Docker image again?
If it fails: can you give more information about your environment? OS, version, etc.

thanks

**Comment by mhdaouas** [comment]
I get this:
> Error response from daemon: Get https://registry.gitlab.com/v2/zatosource/docker-registry/quickstart/manifests/3.1-py3: Get https://gitlab.com/jwt/auth?scope=repository%3Azatosource%2Fdocker-registry%2Fquickstart%3Apull&service=container_registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

For the following command:
`sudo docker pull registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3`

Which command(s) would you like me to issue to get system information (I'm on Centos 8)?

**Comment by DimShadoWWW** [comment]
I installed a CentOS 8, installed Docker CE (https://www.liquidweb.com/kb/how-to-install-docker-on-centos-8/) and pulled the image without problems.

```
[vagrant@localhost ~]$ sudo systemctl start docker
[vagrant@localhost ~]$ sudo docker pull registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3
3.1-py3: Pulling from zatosource/docker-registry/quickstart
5667fdb72017: Pull complete 
d83811f270d5: Pull complete 
ee671aafb583: Pull complete 
7fc152dfb3a6: Pull complete 
a670657024e0: Pull complete 
152f12ffd145: Pull complete 
2aaf374da02d: Pull complete 
7d5b10ad0a02: Pull complete 
d4ac8fe79c67: Pull complete 
531309c5fcdd: Pull complete 
5ff7f89f4bc0: Pull complete 
afaa9e951b09: Pull complete 
429398dc2822: Pull complete 
db6cf49881ca: Pull complete 
4043206c6251: Pull complete 
d6824f5557f9: Pull complete 
f7a5e6af3dea: Pull complete 
5200c7aed759: Pull complete 
6445be6ecd67: Pull complete 
e24c62ad7b0b: Pull complete 
66a0708e043a: Pull complete 
48d74a9a9000: Pull complete 
a37387243246: Pull complete 
d8425cb719c3: Pull complete 
23abdc444a8c: Pull complete 
d9263c3aedaa: Pull complete 
Digest: sha256:551eb25bc95ef223cf0cc0e104c2b3ebb857a1efcd6e9e1cd672bf2f6f5f1858
Status: Downloaded newer image for registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3
registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3
```

Can you try this: `curl -v https://registry.gitlab.com/v2/zatosource/docker-registry/quickstart/manifests/3.1-py3`

Inf everything is OK, you should get this as the response:
```json
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"zatosource/docker-registry/quickstart","Action":"pull"}]}]}
```
This error is not because it need authentication to pull the image, but because of other differences of using `curl` and not `docker pull` (like headers)

**Comment by mhdaouas** [comment]
It looks OK. I still don't understand from where the problem comes. FYI, I'm behind a corporate proxy.

`curl -v https://registry.gitlab.com/v2/zatosource/docker-registry/quickstart/manifests/3.1-py3`

> *   Trying 35.227.35.254...
> * TCP_NODELAY set
> * Connected to registry.gitlab.com (35.227.35.254) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>   CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: CN=registry.gitlab.com
> *  start date: Mar 24 00:00:00 2020 GMT
> *  expire date: May 22 23:59:59 2021 GMT
> *  subjectAltName: host "registry.gitlab.com" matched cert's "registry.gitlab.com"
> *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
> *  SSL certificate verify ok.
> > GET /v2/zatosource/docker-registry/quickstart/manifests/3.1-py3 HTTP/1.1
> > Host: registry.gitlab.com
> > User-Agent: curl/7.61.1
> > Accept: */*
> >
> < HTTP/1.1 401 Unauthorized
> < Content-Type: application/json; charset=utf-8
> < Docker-Distribution-Api-Version: registry/2.0
> < Www-Authenticate: Bearer realm="https://gitlab.com/jwt/auth",service="container_registry",scope="repository:zatosource/docker-registry/quickstart:pull"
> < X-Content-Type-Options: nosniff
> < Date: Thu, 12 Nov 2020 11:00:55 GMT
> < Content-Length: 180
> <
> {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"zatosource/docker-registry/quickstart","Action":"pull"}]}]}
> * Connection #0 to host registry.gitlab.com left intact
>

**Comment by dsuch** [comment]
@mhdaouas If you are behind a proxy then please discuss the matter with its administrators as at this point it is practically 100% guaranteed it is the proxy that is closing the connection prematurely, e.g. it may have some limits as to the max. file size or connection timeout that need to be adjusted for your needs.

Alternatively, you can just install Zato from a Linux package or source code - the result will be exactly the same in terms of the Zato version installed.

https://zato.io/docs/admin/guide/install/index.html

**Comment by dsuch** [comment]
Hello again,

if that is fine with you, @mhdaouas, I am closing the ticket. Unfortunately, there is not much that we can add here given that it looks to be a factor external to Zato.

However, please feel free to re-open any time or to submit a new ticket if there is anything you would like to add.

Thanks.
