### ISSUE TITLE
CORS Issue: https Support

### ISSUE THREAD

**Issue by rashmireddy2719** [zatosource/zato#1097]
Access to XMLHttpRequest at 'http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by dsuch** [comment]
Hello @rashmireddy2719,

I am not sure if that is not a mistake? This is a repository for [Zato](https://zato.io) and this ticket is I am not really sure about what software, possibly JavaScript?

Regards.
