### ISSUE TITLE
Zato backup and migration.

### ISSUE THREAD

**Issue by fenist19** [zatosource/zato#1108]
Hello. I need move our zato cluster from rancher to kubernetes. But we have some questions.
Do you have instruction for zato migration, backup and restore database and cluster?

**Comment by dsuch** [comment]
Hello,

generally, you need to create a new environment, use [enmasse](https://zato.io/docs/admin/guide/enmasse.html) to move your objects, deploy your services and this is the whole process.

How to do it exactly differs between users, everyone automates such tasks in a different way.

In particular, currently, we do not have any support for Rancher so we will not be able to assist in migration from this platform. That support is planned, it is just not available right now.
