### ISSUE TITLE
centos7 support

### ISSUE THREAD

**Issue by githubhaotian** [zatosource/zato#1113]
Hello, when will zato3.1 be released on CentOS7?

**Comment by dsuch** [comment]
Hello,

Zato 3.1 has always worked under RHEL or CentOS 7 - you can find the installation instructions here:

https://zato.io/docs/admin/guide/install/py3/rhel.html

**Comment by githubhaotian** [comment]
We have seen this document, but I found that the version I got was different from the latest version on GitHub by using "Yum check update"，pls update the source of yum.

**Comment by dsuch** [comment]
Please describe fully, step by step, exactly what is that you observe as opposed to what you expected. Otherwise, I do not understand what is that you need.

**Comment by githubhaotian** [comment]
The current view of zato -- version is zato 3.1 + rev.544100e-py3.6.9

, but this code is different from GitHub. Can you provide the latest centos7 Yum source.

**Comment by githubhaotian** [comment]
I come from China, now I have a little thing, hope to continue to communicate tomorrow. Nice to meet you. It's a pleasure to see your zato blog.

**Comment by dsuch** [comment]
After you install Zato from a package, .rpm or .deb, you also need to install the latest updates which brings your installation up to date with what is on GitHub.

Please check the installation instructions again and follow all of them - this will install updates.

**Comment by dsuch** [comment]
Hello again,

have you been able to update your installation per the instructions? Is everything fine?

Thanks.
