### ISSUE TITLE
Can't edit an interval-based job

### ISSUE THREAD

**Issue by bbqi** [zatosource/zato#1115]
try change an interval-based job,such as 'zato.outgoing.sql.auto-ping', I can't find and select an service 'zato.outgoing.sql.auto-ping', submit failed. service is a required field.

zato version : Zato 3.1+rev.c0bbca64c-py3.6.8

![image](https://user-images.githubusercontent.com/60316749/104526316-04e45a00-563d-11eb-8995-26c2fe00c6d5.png)

**Comment by dsuch** [comment]
Hello,

thank you for the ticket - yes, it works as designed. By default you cannot list internal services and, consequently, you cannot assign them to scheduler jobs. Such internal jobs should not be usually modified, hence the protection.

But one thing that I think can be changed is that perhaps in version 3.2 we will simply stop to display all or most of the internal jobs. In this way, there will be no question why they cannot be modified.

Please let me know if you observe the same with your own jobs, if not, then everything is fine here.

Regards.

**Comment by bbqi** [comment]
Thanks.
