### ISSUE TITLE
About build zato offline installation package rpm

### ISSUE THREAD

**Issue by githubhaotian** [zatosource/zato#1118]
Hello, dear author, I'm running . / build- zato.sh Support / 3.1 3.1.0 after using this command, an error appears in the image provided below, which seems like due to rpmbuild - ba zato.spec There is a problem with the command encoding format in this script. How can I solve it
![69887e8610ec5e5ad11506520788f0d](https://user-images.githubusercontent.com/34534776/105022581-e50dc580-5a84-11eb-8003-658266fcdc00.png)
![c0a70b35176bc73f8791b33ae03a1f4](https://user-images.githubusercontent.com/34534776/105022604-ea6b1000-5a84-11eb-845b-9c8429b976e3.png)

**Comment by dsuch** [comment]
I am closing this ticket. If you would like to reopen it, please provide exact instructions how to reproduce it, step by step. Thank you.
