### ISSUE TITLE
Cannot install on CentOS 7

### ISSUE THREAD

**Issue by x011** [zatosource/zato#1119]
I'm following the ZATO  [installation instructions for CentOS ](https://zato.io/docs/admin/guide/install/rhel.html), but the process fails on `yum check-update` with error:

`https://zato.io/repo/stable/3.2/rhel/el7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

Any idea what's causing this and how to fix it?

**Comment by DimShadoWWW** [comment]
Hello @x011 ,
Please, can you try again?

Thank you

**Comment by x011** [comment]
Solved after installing patch:

`yum install patch`

All set, thank you.
