### ISSUE TITLE
Function format_exc must not be called with error as argument 

### ISSUE THREAD

**Issue by AndreiPanasuk** [zatosource/zato#1137]
Hi!
In many case function **format_exc** is called with  e (error type) as argument.  This results in an error because the function definition does not assume this argument 
````python
    def format_exc(limit=None, chain=True):

**Comment by dsuch** [comment]
Hello again - before you open more tickets, there is something you need to understand.

No one will be looking into what you open if you keep saying "there is an error", "many places", without information what your exact Zato version is and how to reproduce a particular situation.

In other words, if you just say "there is an error", I will have no choice but to close a ticket.

You get the software for for free and it is your job to provide all the details that are needed to support you.

**Comment by dsuch** [comment]
Just like with #1136,  I am closing this ticket for the time being - please read more about participating in open-source projects, about how to open support tickets and then feel free to reopen at any time. Thanks.

**Comment by AndreiPanasuk** [comment]
No need to be offended, whoever is not wrong does not work 
This error examples:
code/.zato-src/zato-server/src/zato/server/connection/__init__.py line 112
code/.zato-src/zato-common/src/zato/common/wsx_client.py, line 432
code/.zato-src/zato-server/src/zato/server/connection/http_soap/url_data.py, line 487
...

**Comment by dsuch** [comment]
I am not offended in any way. Indeed, I am thankful for your reporting the tickets. But I simply refuse to work on them if they are not opened properly, that is everything.

**Comment by AndreiPanasuk** [comment]
Ok, but no new errors should be thrown during error handling. To find such situations, it is enough to search for the expression
````log
format_exc(e
