### ISSUE TITLE
curl ide-deploy

### ISSUE THREAD

**Issue by morandalex** [zatosource/zato#1155]
Hello, is it possible ide-deploy services using curl? for example , if I do 

`curl -X POST -H 'Content-Type:application/json' http://localhost:17010/ide-deploy -d '{"username":"ide_publisher", "password":"mypassword"}' ; echo`

the response is: 
`{"result":"Error","cid":"b7f78e1be0841def4702de1","details":"You are not allowed to access this resource"}`
 
What is wrong ?

**Comment by morandalex** [comment]
My version is :  Zato 3.2+rev.55a08d8-py3.6.9

I changed pwd here 

![image](https://user-images.githubusercontent.com/9484568/117838614-c6714b80-b27a-11eb-80ed-0049d79130d3.png)

then : 
`tail -f server.log `

2021-05-11 15:01:45,550 - WARNING - 17200:DummyThread-27 - zato.server.connection.http_soap.url_data:0 - None of RBAC definitions allowed request in, cid:`8d9a411df380629b1d65cf58`
2021-05-11 15:01:45,553 - ERROR - 17200:DummyThread-27 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`8d9a411df380629b1d65cf58`, status_code:`HTTPStatus.UNAUTHORIZED`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 329, in dispatch
    sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 648, in check_security
    sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 638, in check_rbac_delegated_security
    raise Unauthorized(cid, 'You are not allowed to access this resource', auth_type)
zato.common.exception.Unauthorized: <Unauthorized at 0x7fa63eca0d68 cid:`8d9a411df380629b1d65cf58`, msg:`You are not allowed to access this resource`>

**Comment by dsuch** [comment]
Great, I will close the ticket in that case. Thanks.

**Comment by dsuch** [comment]
Ah, I did not realise that there was something else.

Do you need to do it using curl? It is easier to deploy services from command line simply by copying them to hot-deploy directories.

For instance, if path to your server is /my/path/server then you will have a directory called /my/path/server/pickup/incoming/services and you can just use cp from command line to put Python modules there - they will go to all the servers in the cluster automatically.

E.g.

$ cp myapi.py /my/path/server/pickup/incoming/services

You can even run git clone in the directory directly and then git pull to install the latest code.

**Comment by dsuch** [comment]
Hello @morandalex,

there is one more note - starting with Zato 3.2, you can always define your own custom directories to pick up Python modules from.

Open pickup.conf and add an entry at the bottom:

```ini
[hot-deploy.user.my_label>]
pickup_from=/path/to/a/directory/with/services
```

.. where "my_label" is a string label just for your convenience and "hot-deploy.user" is a special prefix that you need to keep. You need to restart the servers afterwards.

Now, you can deploy on save directly from any arbitrary directory in the file system, e.g. straight from your git clone.

**Comment by dsuch** [comment]
Hello @morandalex,

I visited https://morandi.services but I could not find your contact details.

Can you please tell me how I can contact you directly? My email is dsuch at zato.io. Thanks.
