### ISSUE TITLE
To further simplify building MQ Services, it would be great if there was a simple "reply"" function 

### ISSUE THREAD

**Issue by hondab** [zatosource/zato#1156]
The zato IBM MQ "channel/service" capability is pretty good and useable, it would be awesome if in the code one could just need to invoke self.reply.payload to return a response to the replyToQueue in the incoming MQMD.

**Comment by dsuch** [comment]
Thanks @hondab - this is a nice suggestion, I will keep it in mind to include it in one of the future updates.

Is there perhaps anything else that you can suggest or you were thinking about?

Regards.

**Comment by hondab** [comment]
Hi Dariusz,

Awesome!

So I am soo impressed with Zato and integration philosophy! And given that
I have almost 50 years in DP/IT under my belt, that is saying something.

I have been pestering my son who runs the MQAttach company who mainly works
in the MQ/BTM MQ/MFT HIPAA Integration space where IBM IIB/ACE/ITX is
heavily used, but he is looking to move away from the IBM stack as they are
getting too costly and overly complex for what the customer base is looking
for today, He loves MQ, but is not married to the other IBM parts.

I myself am working for Prolifics, as an Integration Advisor / Consultant
and since we have a CTO etc etc, I have started to promote Zato to my
colleagues and just today to our CTO who is very much interested in what
Zato can help with, in the FHIR space as that is where his interest is
currently at, as he has something called Quick FHIR that he built on the
back of the IBM API Management solution which he is causing some push back
from prospective customers because of sticker shock.

Would love to talk to you sometime, so if you are able to call via Skype my
handle is mayoonmb or my cell +1-813-638-7231.

Look forward to continuing this discussion.


Best Regards

Honda
