### ISSUE TITLE
zato3.2 latest version Pub/Sub is not working properly

### ISSUE THREAD

**Issue by libigfat** [zatosource/zato#1178]
zato3.2 latest version Pub/Sub is not working properly.
zato version Zato 3.2+rev.e9746db-py3.8.10-ubuntu.20.04-focal

**Comment by libigfat** [comment]
May this problem be fixed?

**Comment by dsuch** [comment]
This is not the latest version. Please upgrade to the latest one and if anything does not work, you need to tell me **exactly**, **step by step** what does not work. Otherwise, any tickets saying only "does not work" or "is not work working" will be closed automatically. Thank you.

**Comment by libigfat** [comment]
ok i know it
