### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by saki82** [zatosource/zato#1188]
I am on Windows 10 following the instructions on [Zato.io](https://zato.io/en/docs/3.2/tutorial/01.html).
After invoking "zato quickstart ~\env\my1" i get the following error:
![image](https://user-images.githubusercontent.com/7517450/155422620-7865829b-891f-4db5-8813-e1a991752ffc.png)
typing_extensions is already installed, what is the issue?
Thank you!

**Comment by sampathpagolu** [comment]
Did you try this article: https://zato.io/en/docs/3.2/dev/libs/pip.html

**Comment by saki82** [comment]
Thanks @sampathpagolu , i found the issue.
It was in the windows_update.bat which called "environment.py" instead of "zato_environment.py".
Fixed it in PR #1189
