### ISSUE TITLE
inotifyx issue 

### ISSUE THREAD

**Issue by ranjith1397** [zatosource/zato#1212]
Hello,

Because of the Current changes in the inotifyx module, zato 3.1 docker image is not working as expected. While trying to create the container with the zato 3.1 docker image, it fails with the below error. 

WARNING: Generating metadata for package inotifyx produced metadata for project name zato-ext-inotifyx. Fix your #egg=inotifyx fragments.
WARNING: Discarding https://github.com/dsuch/inotifyx/archive/main.zip#egg=inotifyx. Requested zato-ext-inotifyx from **https://github.com/dsuch/inotifyx/archive/main.zip#egg=inotifyx (from -r /opt/zato/current/requirements.txt (line 164)) has inconsistent name: filename has 'inotifyx', but metadata has 'zato-ext-inotifyx'**

Could not find a version that satisfies the requirement inotifyx (unavailable) (from versions: 0.2.1, 0.2.2)

Attaching the file below where the changes broken the image for your reference.

<img width="473" alt="inotifyx" src="https://user-images.githubusercontent.com/101089101/205282126-e7d718e9-63f0-42bd-a3dc-87e414c3a171.png">

Git Hub commit link: https://github.com/dsuch/zato-ext-inotifyx/commit/8a073ea728d11d7bfd77e155b663cdb455328a17

Regards.

**Comment by dsuch** [comment]
Hello,

if there is anything that you need, please feel free to reopen this ticket using full sentences and using basic expressions, such as "Hello" or "Thank you" as well.

Otherwise, I do not understand why you opened this ticket and what it is that you are requesting.

Regards.

**Comment by dsuch** [comment]
Hello @ranjith1397 - Zato 3.1 no longer receives free support. If your company still uses this version, please contact me directly via on dsuch@zato.io from your business email. Regards.

**Comment by dsuch** [comment]
Hello @barronkid,

regarding commercial support - I contacted you via email.

About the deleted file - it was done unintentionally and the file was restored several days ago, right after @ranjith1397 opened the ticket. My apologies for that and I trust that everything works correctly now.

Regards.
