### ISSUE TITLE
unwanted csimdjson.Array conversion

### ISSUE THREAD

**Issue by LordShion** [zatosource/zato#1213]
Zato 3.2+rev.51ced897-py3.8.10-ubuntu.20.04-focal

I created a simple service as in the documentation says
```
# -*- coding: utf-8 -*-
from zato.server.service import Service

class TestResponse(Service):
    """ Returns details of a user by the person's ID.
    """
    name = "api.test.response"

    def handle(self):
        self.logger.info(self.request.payload)
        # For now, return static data only
        self.response.payload = {
            "user_name": "John Doe",
            "user_type": "SRT"
        }
```

in the invoker interface, when I put for exemple a simple json payload no problem
I send 
`{"test": "test"}` 
it replies 
`{"user_name": "John Doe", "user_type": "SRT"}`

but if I send
`[{"test": "test"}]`
 it seems to convert the request.payload in a csimdjson.Array, and it seems zato tries to convert reponse.payload also in a csimdjson.Array but it end with this error:
```2023-01-11 13:27:41,908 - ERROR - 377209:Dummy-108 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`7e906b5e441cb5d18889af5d`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 343, in dispatch
    response = self.request_handler.handle(cid, url_match, channel_item, wsgi_environ,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 705, in handle
    response = service.update_handle(self._set_response_data, service, raw_request,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 800, in update_handle
    payload = payload_from_request(server.json_parser, cid, raw_request, data_format, transport, channel_item)
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/util/api.py", line 499, in payload_from_request
    payload = json_parser.parse(request_bytes)
  File "simdjson/csimdjson.pyx", line 435, in csimdjson.Parser.parse
RuntimeError: Tried to re-use a parser while simdjson.Object and/or simdjson.Array objects still exist referencing the old parser.```
and then all zato freezes for some seconds to sometimes 1 minute depending on the size or the number of jsons

this is really annoying since I have many services wich where receiving arrays in zato 3.1 array where kept as jsons , and this problem makes me impossible to move on 3.2
But maybe I'm doing wrong and must convert also my responses as  csimdjson.Arrays  ?

**Comment by dsuch** [comment]
Hello Filipe,

please contact me directly on dsuch@zato.io from your business email.

Regards.
