### ISSUE TITLE
AMQP KeyError: 'address' after trying to publish

### ISSUE THREAD

**Issue by SikiFn** [zatosource/zato#1214]
Hello,

Following this tutorial: https://zato.io/en/docs/3.2/tutorial/linux/cli/02.html

When you reach this part "Pinging AMQP with publications" and you try to submit a message the following error will show in the logs:

> 2023-01-28 07:41:29,142 - ERROR - 3170:Dummy-2035 - zato:0 - Could not handle broker message: (DEFINITION_AMQP_EDIT:100601) `Bunch(action='100601', cluster_id=1, config_cid='definition.amqp.create_edit.server1@quickstart-416288.35a929e10a00187dc748f17f', frame_max=131072, heartbeat=1, host='tutorial.zato.io', id=1, name='Fraud Detection Definition', old_name='Fraud Detection Definition', opaque1=None, password='PJs4TEeui118A', port=25701, source_server='server1@quickstart-416288', username='api', vhost='tutorial')`, e:`Traceback (most recent call last):
>   File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/dacite/core.py", line 59, in from_dict
>     field_data = data[field.name]
> KeyError: 'address'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/dacite/core.py", line 71, in from_dict
>     value = get_default_value_for_field(field)
>   File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
>     raise DefaultValueNotFoundError()
> dacite.dataclasses.DefaultValueNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/zato/3.2.0/code/zato-broker/src/zato/broker/__init__.py", line 48, in on_broker_msg
>     func(msg)
>   File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/amqp_.py", line 61, in on_broker_msg_DEFINITION_AMQP_EDIT
>     msg = AMQPConnectorConfig.from_dict(msg) # type: ignore
>   File "/opt/zato/3.2.0/code/zato-common/src/zato/common/model/amqp_.py", line 38, in from_dict
>     return from_dict(AMQPConnectorConfig, config_dict)
>   File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/dacite/core.py", line 75, in from_dict
>     raise MissingValueError(field.name)
> dacite.exceptions.MissingValueError: missing value for field "address"

**Comment by dsuch** [comment]
Hello @SikiFn,

thank you for the message. This is being seen to - I will let you know once the work is finished.

Regards.

**Comment by dsuch** [comment]
This is done. Note that the AMQP connection details are changed now: https://zato.io/en/docs/3.2/tutorial/linux/cli/02.html

Regards.
