### ISSUE TITLE
Boundary key missing in the Content-Type header of a multipart/form-data outgoing REST connection with multiple sections

### ISSUE THREAD

**Issue by calcomsrl** [zatosource/zato#1215]
Hello,
when sending an outgoing REST connection with multiple sections using the multipart/form-data Content-Type, the boundary key is not being attached to the Content-Type header. This results in an invalid request being sent to the server, as the server cannot identify the boundaries between different sections of the message.

Steps to reproduce:

1. Create a REST connection that sends a multipart/form-data request with multiple sections.
2. Observe the outgoing request headers and check for the presence of the boundary key in the Content-Type header.
3. If the boundary key is not present, attempt to send the request and observe any errors or unexpected behavior from the server.

Expected result:
The boundary key should be attached to the Content-Type header of the outgoing request, allowing the server to properly identify the boundaries between different sections of the message.

Actual result:
The boundary key is missing from the Content-Type header of the outgoing request, resulting in an invalid request being sent to the server and potentially causing unexpected errors or behavior.

Regards

**Comment by dsuch** [comment]
Thank you, I confirm the reception of your message. Regards.
