### ISSUE TITLE
Upgrade Requests Dependency to 2.1.0

### ISSUE THREAD

**Issue by dixonwh** [zatosource/zato#132]
Hello,

We are using Zato to host services which dynamically create outbound connections, based on metadata configuration.s Our service code uses requests 2.x to make these connections.

Requests 2.x isn't backwards compatible with 1.x or 0.x which are versions used in Zato's master branch and current 1.1 version.

Would there be any interest in updating the master branch to use Requests 2.x? If so, I'd be happy to take a look at it, and send a pull request.

Thanks,

Dixon Whitmire
PokitDok, Inc

**Comment by dsuch** [comment]
Thanks @dixonwh - we are now using requests 2.7.0+
