### ISSUE TITLE
Make Python clients support other HTTP methods

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#204]
Right now Python clients will only POST data, we should support other methods as well.

**Comment by dj-xatra** [comment]
My use case: getting and updating Xwiki pages using the [RESTful API](http://platform.xwiki.org/xwiki/bin/view/Features/XWikiRESTfulAPI#HPageresources).

**Comment by dsuch** [comment]
Hi @dj-xatra - actually, this is an old ticket that I can see has no milestone set and that's why it's not closed yet.

You can use .get, .post, .put, .delete and .patch.

Will that suffice?

**Comment by dj-xatra** [comment]
Those methods are fine for use in service code. But how would I update a wiki page with a pub/sub callback URL to XWiki if that needs PUT?

**Comment by dsuch** [comment]
Sorry, I don't know what XWiki is and how its PUT method works - can you link me to an exact API usage example?

Thanks.

**Comment by dsuch** [comment]
Ok, I think I can see where you're coming from. Right now the method to invoke callback URLs is set in code to be .post. Please open a new ticket if you'd like for it to be configurable in the next release.

Right now this is POST. A way to deal with it would be to set the callback URL to your own Zato server endpoint on localhost and have a JSONAdapter listen for messages, acting as a thin proxy, so the messages can be translated to PUT for XWiki's purposes:

https://zato.io/docs/progguide/rest/json-adapter.html

I'm closing this ticket since it's not really related to pub/sub's verbs. Thanks!
