### ISSUE TITLE
Add full LDAP

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#225]
Add all the pieces in addition to what has been added in #157

**Comment by telenieko** [comment]
Hi, just found this ticket looking about Zato's LDAP support and saw #157 is closed. I believe this is not in 2.0, right? Any plans on merging this for next Zato?

**Comment by dsuch** [comment]
Hi @telenieko - you are right that it fell off the track but it is still planned.

However, what has changed since the time the ticket was created is that for 2.1 there is planned a means to create connections plugins.

https://mailman-mail5.webfaction.com/pipermail/zato-discuss/2015-January/000796.html

The deal is that adding new connection types, while not particularly difficult, still requires a good knowledge of Zato's internals and obviously, if you are interested in LDAP then you are interested in LDAP, not necessarily in Zato's core details :-)

So I think LDAP could be one interesting example of how to add a plug-in. Naturally, it could land as a built-in as well with time, nothing rules it out.

Would be fantastic if you joined the discussion on the mailing list - perhaps you're interested in other technologies as plug-ins as well?

Thanks.

**Comment by telenieko** [comment]
Hi,
Thanks for the tips, I'll take a look at the mailling list :-) My main interest now is in LDAP as I was looking at Zato to fill the gap between our django intranet and that very-ugly monster called Active Directory (ie: we have some dirty scripts to sync up stuff, etc).

The plugin plan seems awesome, in fact, I can tell you, when I read this ticket (#157) I got scared to death of how hard adding something "so simple" could be. @tkrajca has all my respect for having worked so hard!

**Comment by dsuch** [comment]
Yes, well, these are the internals - every step is taken to make things look simple from a user's perspective but as you have checked it out - there's quite a lot going on to make sure everything is going on smoothly in such a distributed environment :-)

**Comment by urc** [comment]
As it has been quiet on this front for two years now, is this still being developed somewhere, as a feature? Or is everyone just building their own custom code for this? Thanks!

**Comment by dsuch** [comment]
Hello @urc,

it's not been added to the core yet.

However, we now have [Vault](https://www.vaultproject.io/) connections in the GitHub version. Have a look at this blog post: https://zato.io/blog/posts/securing-apis-zato-vault.html

Now, Vault is a very nice piece of technology that acts as a frontend to multiple authentication stores and we now have [Tokens](https://www.vaultproject.io/docs/auth/token.html), [Username]() & [Password](https://www.vaultproject.io/docs/auth/userpass.html) as well as [GitHub](https://www.vaultproject.io/docs/auth/github.html) integration for Vault-secured channels.

Adding [LDAP](https://www.vaultproject.io/docs/auth/ldap.html) to it will be possible but there is no effort in this direction right now. If it's something that you would like to see added as a priority please contact me on dsuch@zato.io and I will be happy to discuss it with you!

**Comment by urc** [comment]
@dsuch We're looking at it as a way of managing an LDAP directory, providing an API for it, for things like user registration, password resets, and so on. So not just to authenticate against :)

We'll look at something else, or front it with a REST API instead. Thanks!

**Comment by dsuch** [comment]
@urc Sure, I understand it. Adding LDAP outgoing connections to [already existing ones](https://zato.io/docs/progguide/outconn/overview.html) is certainly doable as well and in fact would not be much more difficult than using LDAP as an authentication mechanism alone. Again, feel free to contact me directly and this can be arranged.
