### ISSUE TITLE
Add MongoDB outgoing connections

### ISSUE THREAD

**Issue by csala** [zatosource/zato#234]

**Comment by vabue** [comment]
It would be very helpful. I use mongo in half of Zato services.

**Comment by prasadh13** [comment]
Any update on this ticket?

**Comment by dsuch** [comment]
Hello @prasadh13,

there has been no work on this ticket and there are no plans to do it for 3.0, which will be released this year, unless someone sponsors it - please contact me on dsuch@zato.io if you'd like to discuss it.

Regards.

**Comment by dsuch** [comment]
This is done:

https://zato.io/blog/posts/mongodb.html
