### ISSUE TITLE
Parallel requests (like Oracle's Split/Join)

### ISSUE THREAD

**Issue by davinirjr** [zatosource/zato#274]
As of documentation at http://docs.oracle.com/cd/E21764_01/doc.1111/e15867/splitjoin_console.htm: Split-Joins let you send message invocations in parallel (in addition to sequentially) and to aggregate the responses. 

Maybe using GRequests (https://github.com/kennethreitz/grequests).

**Comment by dsuch** [comment]
Hi,

the feature will be called fan-out/fan-in and is slated to be delivered for the upcoming Zato 2.0 release.

https://zato.io/docs/2.0/

**Comment by dsuch** [comment]
In master since 4cd00cdbc12bc6d56a2645a827c02e1dd26052b2, thanks @davinirjr !

**Comment by davinirjr** [comment]
What a masterpiece, @dsuch, congrats !!!

Whould try it ASAP !!!

**Comment by dsuch** [comment]
For reference - here is documentation:

https://zato.io/docs/2.0/progguide/patterns/fan-out-fan-in.html
