### ISSUE TITLE
Upgrade to Django 1.6

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#277]
We should start using Django 1.6. However - this means going through both how Zato uses Django's API and OpenID to make sure the upgrade goes smoothly.

**Comment by auvipy** [comment]
Django 1.8 LTS on the way

**Comment by dsuch** [comment]
Hello @auvipy,

Do you think it would be easy to upgrade our Django version and perhaps would like to give it a go?

The fact that we are still at 1.3 is due to web-admin's being simply a frontend delegating all the hard work to servers. i.e. it doesn't do much really except for serving HTML, CSS and JS.

https://zato.io/docs/architecture/overview.html

Obviously, it's good be at an LTS so maybe it's something you'd like to contribute?

Many thanks!

**Comment by auvipy** [comment]
I will definitely give it a short as I have I year+ django exp :)

**Comment by dsuch** [comment]
Ok, we have now migrated to Django 1.9.
