### ISSUE TITLE
Small GUI / Usability enhancements - Cluster-selectbox

### ISSUE THREAD

**Issue by thomasez** [zatosource/zato#361]
When only one Cluster, why not just make it default or selected in the select box? On the services page it's "-------", maybe other places aswell.

(Regarding "---------" as empty-value for select boxes, they could have text with "Pick a <foooo>". This is nitpicking, since the users will learn that "------" means a select box and something to click on.)

**Comment by dsuch** [comment]
Done and in master since 6f40a7c - forms are now auto-completed and auto-submitted if there is only one cluster in ODB.
