### ISSUE TITLE
Small GUI / Usability enhancements - Autocomplete

### ISSUE THREAD

**Issue by thomasez** [zatosource/zato#362]
Many places there are text boxes where the user is supposed to edit a service or other name which already exist in the data base and has to match.

I suggest either making select-boxes (which may end up being too large on bit installations?) or add autocomplete.

**Comment by dsuch** [comment]
Done and in master since 6f40a7c8f32c13c8dc970fec5f5a3231f9492d5b - forms are now auto-complete and auto-submitted if there is only one cluster in ODB.

**Comment by dsuch** [comment]
In master since - it's a select box without autocompletion but will work nicely. Can be extended to include autocompletion with time.
