### ISSUE TITLE
pip install zato/ python setup.py install?

### ISSUE THREAD

**Issue by auvipy** [zatosource/zato#368]

**Comment by dsuch** [comment]
Hi @auvipy,

many thanks for opening ticket but pip is not enough. Zato is not just a regular Python package and pip just is not able to handle it.

Please check out the relevant discussion here, but in short:

* There is no benefit in using pip and the drawbacks are many

* There is simply no need for pip, everything works correctly as it is now and any sort of effort could be better directed elsewhere - for instance we have recently started to work on Chef cookbooks for Zato - perhaps you'd like to join in? Me and my colleagues would be very happy to discuss it with you :-)

https://mailman-mail5.webfaction.com/pipermail/zato-discuss/2014-June/000502.html

I'm going to close the ticket in some time. Thanks for understanding.

**Comment by auvipy** [comment]
ok (y)
