### ISSUE TITLE
Bug in traceback formatting hides the actual error

### ISSUE THREAD

**Issue by ElmoVanKielmo** [zatosource/zato#370]
When trying to create quickstart environment I've run into this:

    [zato@falcon-local ~]$ zato quickstart create ~/falcon-zato postgresql localhost 6379 --odb_host localhost --odb_port 5432 --odb_user zato1 --odb_db_name zato1 --verbose
    
    ODB database password (will not be echoed): 
    Enter the odb_password again (will not be echoed): 
    
    Key/value database password (will not be echoed): 
    Enter the kvdb_password again (will not be echoed): 
    [1/8] Certificate authority created
    Traceback (most recent call last):
      File "/opt/zato/2.0.1/code/bin/zato", line 180, in <module>
        sys.exit(zato.cli.zato_command.main())
      File "/opt/zato/2.0.1/code/zato-cli/src/zato/cli/zato_command.py", line 262, in main
        return run_command(get_parser().parse_args())
      File "/opt/zato/2.0.1/code/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
        command_class[args.command](args).run(args)
      File "/opt/zato/2.0.1/code/zato-cli/src/zato/cli/__init__.py", line 489, in run
        self.logger.error(get_full_stack())
      File "/opt/zato/2.0.1/code/zato-common/src/zato/common/util.py", line 828, in get_full_stack
        stackstr += '  ' + traceback.format_exc().lstrip(trc)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3085: ordinal not in range(128)

My OS is CentOS 7. It's a fresh zato installation.

    [zato@falcon-local ~]$ python
    Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
    
    [zato@falcon-local ~]$ uname -a
    Linux falcon-local 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    [zato@falcon-local ~]$ rpm -qa | grep zato
    zato-2.0.1-stable.el7.x86_64

**Comment by dsuch** [comment]
Thanks, it will be made more robust in 2.0.2.

Any chance you could change

```python
stackstr += '  ' + traceback.format_exc().lstrip(trc)
```

to

```python
stackstr += '  ' + traceback.format_exc().lstrip(trc).encode('utf-8')
```

in /opt/zato/2.0.1/code/zato-common/src/zato/common/util.py, line 828? That would make diagnosing it much easier.

By the way, the path to the interpreter is ```~/2.0.1/code/bin/py``` - it's isolated from the underlying OS.

**Comment by dsuch** [comment]
In master since 243ec22618745fad46a5bb03c97af8321855c3eb.
