### ISSUE TITLE
Add checking for updates

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#374]
When servers start, they should check what their version is and compare it against the latest release on zato.io.

However, this should be done only for minor updates. For instance, a server running on 2.0.1 should notify users that 2.0.2 is available but not about 2.1.x.

It should be implemented in a background startup service so as not to increase a server's startup time.

**Comment by davinirjr** [comment]
It would be nice to have a notification (email, log, ...) for updates != minor.

**Comment by dsuch** [comment]
Cool, but the question is how to do it in a non-obtrusive way.

For instance, there are people running 1.1 who prepare to migrate to 2.0 within several months but they do know of 2.0's existence so reminding of it each time servers start would be quite obnoxious.

How about we check for major updates only when servers are already running, say, once a week?

On top of it, let's have two flags in server.ini:

* notify_minor_versions
* notify_major_versions

What do you think?

**Comment by dsuch** [comment]
>  say, once a week?

Or even once a month. The assumption is that upgrading to a major release is a concious act - there's probably not much reason to nag everyone about it?

**Comment by davinirjr** [comment]
Hummm, good one.

Once a week seems fine to me for updating errors or security holes.

But we don't have this time window for releases, right?

And we can't distinguish from bugs/security updates from "normal"
(features) updates...

I'll need to think a little about this, Dariusz...

**Comment by davinirjr** [comment]
Dariousz,

Seems to me that we have the following branches for discution:

0) Checking updates (manually, cron job, REST interface and UI interface);

1) Notifications about updates (email, log, sms?, ...);

2) Applying updates manually, automatically for segurity/bug fixes, or full
auto (shell script(s), and REST interface would be nice).


+1 for concious upgrades !!! :) Some companies like to plan updates and
perform them manually, specially on crucial pieces/components (like ESB).

**Comment by dsuch** [comment]
Done in 5795d726fe0d41094fd2bac25b17149999bef78f.

We notify in server.log (on WARN level) if there are newer minor or major releases:

* Minor - each 60 days
* Major - each 180 days
