### ISSUE TITLE
Small suggestions for the tutorial (docs)

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#383]
Three minor issues that could be improved in the tutorial:
- Contrary to the web-admin, the loadbalancer of the quickstarted cluster is bound to 127.0.0.1, not to 0.0.0.0. So when you want to access it from outside a virtual machine, you need to change that first in load-balancer/config/repo/zato.config or via the web-admin. Maybe this should be mentioned in the tutorial, particularly as the default is different for the loadbalancer and the web-admin.
- In the 2nd incarnation of the GetClientDetails service on the page https://zato.io/docs/tutorial/02.html, the line "config_key = ..." is irritating and should be removed because it is needed only later.
- On the same page, _when you choose Cluster in the menu_ should be changed to _when you choose "Cluster_**s**_" in the menu_.

**Comment by alirizakeles** [comment]
I think one more small improvement would be great. Tutorial is very useful for Zato newbies. In all docs and tutorials 'cluster' means or points something like in quickstarted cluster, a cluster with more than one servers **on the same machine / environment**. 

At least, at the beginning of Tutorial on section "Installing Zato and creating a quickstart cluster" a short explanation should be added.

Thanks.

**Comment by dsuch** [comment]
Hi @alirizakeles,

thanks for the suggestion but I'm not sure what you'd like to change, actually?

Whenever a cluster is mentioned in the documentation, it is any cluster, unless specifically mentioned to be a quickstart one.

In fact, there is no difference between a quickstart cluster and one spread across multiple systems.

Can you please suggest what to add exactly and to which chapter?

Thanks.
