### ISSUE TITLE
Add support for MQTT

### ISSUE THREAD

**Issue by andypiper** [zatosource/zato#39]
http://mqtt.org

There will shortly be a Python client for MQTT (from the mosquitto project) donated to the Eclipse Paho project. That should be a good on-ramp.

**Comment by GertjanvanhetHof** [comment]
What is the status about this. Is MQTT supported by Zato now?

**Comment by dsuch** [comment]
Hello @GertjanvanhetHof,

it's nice to meet you!

We don't have support for MQTT in Zato yet. If you'd like to talk about adding it under a commercial contract - please contact me on dsuch@zato.io and I will be happy to discuss it with you - this can be certainly done.

Regards.

**Comment by dsuch** [comment]
Closing old tickets.
