### ISSUE TITLE
Datetimes are not timezone-aware

### ISSUE THREAD

**Issue by merwok** [zatosource/zato#391]
In https://zato.io/docs/progguide/service-dev.html#service-attributes we see a number of attributes defined like this example: “invocation_time  A datetime.datetime object representing the time a service has been invoked at. Always in UTC.”

One would expect such an object to be a timezone-aware datetime, but a quick inspection shows it is not (the object has no tzinfo).

Changing the code to always use tz-aware datetimes may be tedious and break backward compatibility.  However the docs could be clarified (i.e. mention that the datetime attributes are naïve) to avoid bad surprises.

**Comment by dsuch** [comment]
> One would expect such an object to be a timezone-aware datetime, but a quick inspection shows it 
> is not (the object has no tzinfo).

That's correct - there is no tzinfo.

The docs will be updated. You can safely assume that there is only UTC is used everywhere throughout the platform.

On server side, there is never anything in local TZ.

Local timezones are used only on frontend if configured by users:

https://zato.io/docs/web-admin/settings/main.html

Thanks for the suggestion.

**Comment by merwok** [comment]
Would you like a PR?

**Comment by dsuch** [comment]
> Would you like a PR?

Sure, would be cool!
