### ISSUE TITLE
Check out PyPy

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#392]
A ticket to keep track of the effort related to running Zato on PyPy.

**Comment by vabue** [comment]
Just made some comparison of Zato requirements.txt and [list of PyPy compatible packages](http://packages.pypy.org/). 
```
base32-crockford
bzr
candv
crontab
datadiff
dictalchemy
gevent
lxml
paodate
springpython
texttable
```

are marked as incompatible or missing in the list. Lxml is a big problem for sure.

**Comment by dsuch** [comment]
Closing for now, thanks @vabue !
