### ISSUE TITLE
Update pg8000 and SQLAlchemy

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#406]
Moved over from https://github.com/zatosource/zato-build/issues/21

This can be done but it just so happens that 2.0.3 has just been mostly built, so it will need to wait until 2.0.4.

@cito - what was the exception if you still have it around?

**Comment by Cito** [comment]
I have tried it again and could reproduce it:

* Create a new outgoing SQL connection to a Postgres database.
* Click "Change password"
* Click "Ping"

I get the following error:

    Could not ping the outgoing SQL connection, e:[Traceback (most recent call last):
      File "/opt/zato/2.0.2/zato-web-admin/src/zato/admin/web/views/outgoing/sql.py", line 134, in ping
        response = req.zato.client.invoke('zato.outgoing.sql.ping', {'id':id})
      File "/opt/zato/2.0.2/zato-web-admin/src/zato/admin/middleware.py", line 70, in invoke
        raise Exception(response.inner.text)
    Exception: {"zato_env": {"details": "Traceback (most recent call last):\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 198, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 351, in handle\n    params_priority=channel_item.params_pri)\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/service\/__init__.py\", line 423, in update_handle\n    raise e\nZatoException: Expected elem:[response_time] not found in item:[{u'response_time': u''}]\n", "result": "ZATO_ERROR", "cid": "K06TGMECMEWH4RR6Q4S310BC13FZ"}}
    ]

In the server.log I see the same error, but somewhere before I see also this:

     File "/opt/zato/2.0.2/eggs/pg8000-1.9.10-py2.7.egg/pg8000/core.py", line 1157, in __init__
        raise exc_info()[1]
    TypeError: cannot concatenate 'str' and 'int' objects
    
This is the bug in the pg8000 error handling code.

After replacing the installed versions of pg8000 and SQLAlchemy,

    sed -i "s/SQLAlchemy = 0.9.4/SQLAlchemy = 0.9.9/" zato/code/versions.cfg
    sed -i "s/pg8000 = 1.9.10/pg8000 = 1.10.2/" zato/code/versions.cfg

I could use the Postgres connections without any problems.

**Comment by dsuch** [comment]
Ok, @Cito - we'll postpone the release of 2.0.3 to include this update but I still cannot reproduce it against Zato 2.0.2 and Postgres 9.3 running from an Ubuntu package 9.3.6-0ubuntu0.14.04.

What is yours?

**Comment by Cito** [comment]
I had the issue on Ubuntu 14.04 64bit with Zato 2.0.2 when trying to connect to a remote Postgres 9.2.5 server on a Redhat box.

**Comment by dsuch** [comment]
Thanks @Cito - the versions have been upped and will be included in 2.0.3.

**Comment by Cito** [comment]
The bug is mentioned [here on Stackoverflow](http://stackoverflow.com/questions/24784598/pg8000-postgres-connection-issues-from-python). Allegedly, it happens only on authentication errors, but I got the same error with the correct password.
