### ISSUE TITLE
Import from deleted module zato.common.odb.util

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#409]
In 91bae1f5a430b58ea6cc8b976eacc6a7c2d56399, the module `zato.common.odb.util` has been deleted, but the `__init__.py` file of `zato.common.odb` is still importing from there:

    from zato.common.odb.util import get_engine_url

**Comment by dsuch** [comment]
Thank you @Cito - this is fixed in commit 224ece4e521f753810160e463f9e054c16d378a6
