### ISSUE TITLE
Missing tags in the repository

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#410]
I just checked out the master branch, but it is currently not working because of issue #409.

So I tried to checkout from a branch or tag, but could not find tags for the recent versions 2.0.2 and 2.0.3.

My suggestion is to provide more tags, and maybe to have a develop and a master branch as suggested [here] (http://nvie.com/posts/a-successful-git-branching-model/). The master branch would then always be production ready.

**Comment by dsuch** [comment]
We follow a different model.

* Branch **master** is the development one
* All features are added in feature branches such as **dsuch-f-gh325-add-zato-migrate**
* When a feature is ready it is merged into master
* All stable releases are in **support/$version** such as **support/2.0** for all 2.0.x releases and backports - this is what is production ready
* 99% of time master is stable but still it is a development version and you just happened to have come across that 1% - sorry about it, it will be fixed as soon as possible

As for tags - yes, agreed.

**Comment by Cito** [comment]
Ok, thanks, that model is good enough. After checking out from support/2.0 instead of master, everything worked nicely.

But maybe you could waste a few words about this in the documentation. I suggest adding a section about installing from source on [the page about installing Zato](https://zato.io/docs/admin/guide/install-zato.html). In that section, you could explain the meaning of the various branches.

**Comment by Cito** [comment]
The bug is mentioned [here on Stackoverflow](http://stackoverflow.com/questions/24784598/pg8000-postgres-connection-issues-from-python). Allegedly, it happens only on authentication errors, but I got the same error with the correct password.

**Comment by dsuch** [comment]
Ok, I added the missing 2.0.2 tag and 2.0.3 will have one fore sure.

The docs will be updated as well - https://github.com/zatosource/zato-docs/issues/23

Thanks.
