### ISSUE TITLE
Encoding in web-admin service source code view

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#425]
When I have a service source code with non-ascii strings encoded in UTF-8 and a `# -*- coding: utf-8 -*-` line at the top of the file, the non-ascii chars are not displayed properly in the web-admin interface in the source code view. The response is sent back as UTF-8, but it looks like the source code has been encoded twice.

**Comment by dsuch** [comment]
Ok, I can confirm it - will be working on it now.

**Comment by dsuch** [comment]
Thank you again @Cito - fixed in 5c938003a07d98d02fb023f98e4a47081cf505fb and will be released in 2.0.4.
