### ISSUE TITLE
Tags for services

### ISSUE THREAD

**Issue by vabue** [zatosource/zato#434]
Now the only method of service grouping is name convention.
Tags or groups of services would be very useful.

**Comment by dsuch** [comment]
Hi @vabue - yes, the idea is to add resource tagging to everything, services, connections, anything that we have.

This will work with enmasse as well + will be selectable in GUI so you will be able to tag something as v3.9.1 and have the GUI display stuff related to that version of your software only.

**Comment by dsuch** [comment]
Closing old tickets.
