### ISSUE TITLE
Very open permissions on private keys

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#440]
Examples:

~~~
$ ls -l ca/ca-material/ca-key.pem
-rw-rw-r-- 1 zato zato 3406 Apr 29 10:43 ca/ca-material/ca-key.pem
$ ls -l server1/config/repo/zato-server-priv-key.pem
-rw-rw-r-- 1 zato zato 3272 Apr 29 10:43 server1/config/repo/zato-server-priv-key.pem
~~~

IMO these should be at least 640 or tighter.

**Comment by dsuch** [comment]
Done in 455a77e8098301d3ee03ea77286e06b027cbf02f - will be released in 2.0.6.

Made it 640 in the end, I contemplated 600 as in openssl but in the end settled on 640 indeed.
