### ISSUE TITLE
ZATO_BIN with full path

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato#445]
Just a little one,when creating quickstart cluster, the generated scripts contain the variable ZATO_BIN=zato, I think that a full path would be better, it would avoid the necessity to add it to PATH.

The solution is to pass a full path in quistart.py

```
zato_qs_start_head = zato_qs_start_head_template.format(zato_bin=zato_bin, script_dir=script_dir, cluster_name=cluster_name, start_steps=start_steps)
```

and

```
        zato_qs_stop = zato_qs_stop_template.format(zato_bin=zato_bin, script_dir=script_dir, cluster_name=cluster_name, stop_steps=stop_steps, stop_servers=stop_servers)
```

instead of 

```
zato_bin=zato_bin
```

something like

```
zato_bin=os.path.join(zato_install_bin_path, zato_bin)
```

**Comment by candlerb** [comment]
One problem with that suggestion is that if you upgrade the version of zato you don't want to have to change all your scripts to point to the new location.

At the moment zato deals with this by creating `/opt/zato/.zato-path` and sourcing that from `~zato/.profile`

It might be simpler if there were a symlink e.g. `/opt/zato/current` -> `/opt/zato/x.x.x`

**Comment by pedrudehuere** [comment]
yes I think the simlink would be better

**Comment by dsuch** [comment]
Hi there,

I'm discussing it with @andy-wr on a side and this can be done.

But what is the advantage in your use cases of adding the additional symlink?

The path to the binary will be placed on PATH at any rate so I'd just like to understand if there is anything additional that ```/opt/zato/current``` will cover in your environments?

**Comment by candlerb** [comment]
For me, it's the ability to have fixed paths in scripts and documentation, without having to rely on `$PATH` being set correctly.

(Whilst you can ensure that PATH is set in login shells, in my experience non-login shells will trip you up - e.g. things spawned from cron; things run from sudo without -E)

So I'd rather have it either one way or the other:

* Remove the version number from the path entirely, and just put everything directly under /opt/zato; or
* Include the version number in the path, allow multiple /opt/zato/x.x.x packages to be installed side by side, and have a symlink pointing to the currently selected one

**Comment by dsuch** [comment]
Right, OK, makes sense - scripts and docs are certainly easier to author if the path is fixed.

@andy-wr
