### ISSUE TITLE
Cleaner package versioning

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#447]
The way that zato currently handles upgrades - making a copy of all existing files under `/opt/zato/backup/<version>.<timestamp>` - is very ugly, and doesn't make it easy to do a rollback.

If zato wants to have multiple versions installed concurrently, then I suggest the right way to do this is to handle it the same way that multiple versions of the linux kernel are handled in Ubuntu/Debian.
1. Have an empty metapackage named "zato", version 2.0.3
2. Have a package whose name is "zato-2.0.3" version 2.0.3, which contains all the files under /opt/zato/2.0.3
3. Make the "zato" metapackage declare `Depends: zato-2.0.3`

When you release a new version then you release a new package "zato-2.0.4" with files under /opt/zato/2.0.4, and at the same time you release a new version of the metapackage "zato" with version 2.0.4, which depends on "zato-2.0.4"

Then an apt-get upgrade will:
- pull in the upgraded zato metapackage
- pull in zato-2.0.4 as a dependency
- leave zato-2.0.3 in place; but as there is no longer any dependency, it can be removed when the admin is sure they no longer need it

It is then useful to have a symlink from `/opt/zato/current` to `/opt/zato/x.x.x`. This symlink can either be included within the zato metapackage (in which case it's swung as soon as you update), or can be updated using a command (in which case the admin decides when they are ready to switch), e.g.

```
zato upgrade --to 2.0.4
```

Ganeti is another example of a system which has been [packaged this way](https://groups.google.com/forum/#!topic/ganeti/S3tE5NmUJgI).

**Comment by dsuch** [comment]
Hi @candlerb ,

> If zato wants to have multiple versions installed concurrently, then I suggest
> the right way to do this is to handle it the same way that multiple versions 
> of the linux kernel are handled in Ubuntu/Debian.

there isn't any such desire, the only reason /opt/zato/backup gets created is to keep backups of older versions because people can update their versions.cfg or place additional libraries in zato_extra_paths and they all shouldn't be lost just like that during an upgrade.

Can you please say more why you find rollbacks not an easy task?

Thanks.

**Comment by candlerb** [comment]
> there isn't any such desire, the only reason /opt/zato/backup gets created is to keep backups of older versions because people can update their versions.cfg or place additional libraries in zato_extra_paths and they all shouldn't be lost just like that during an upgrade.

Why would zato_extra_paths be lost on an upgrade? Any files or symlinks which you have created yourself (which were not part of the original package) are not removed by the package manager. It will leave the directory present with the old files.

> Can you please say more why you find rollbacks not an easy task?

Well, a rollback of the form

~~~
apt-get install zato==2.0.2
~~~

is possible - as long as you trust that the older package version is still present in the package repository. The contents of /opt/zato/backup are therefore not really any use.

OTOH, if you want to keep the old versions of zato around, the way I've outlined is cleaner - and it gives you the option of a safe, guaranteed, instant rollback.

**Comment by dsuch** [comment]
Ok, thanks @candlerb.

The idea with backups happens to have been mine, previously the whole of the package was deleted during upgrades.

But I'll let @andy-wr speak up, along with @rafal-k they are chief people before everything to do with our packages.

**Comment by candlerb** [comment]
Sure. To be honest #379 is a more serious problem for me.

**Comment by andy-wr** [comment]
#447 It's a good idea, but I need some time to think it over - it has to be planned and designed together with RPMs for RHEL/CentOS releases

**Comment by candlerb** [comment]
There is another related problem: it looks like you don't keep older versions of the package in your repo, so if a user needs to install an older version, they are out of luck.

~~~
# apt-get install zato=2.0.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '2.0.3' for 'zato' was not found

# apt-cache show zato | grep Version:
Version: 2.0.4-stable-trusty
~~~

Due to #454 I was going to try to do an "official" downgrade (install version 2.0.3, use `apt-mark hold` to prevent it auto-upgrading again), but this isn't possible if the 2.0.3 package is not in the repo.

So I had to do a kludged manual rollback:

* `mv /opt/zato/backup/2.0.3.<timestamp> /opt/zato/2.0.3`
* `vi /opt/zato/.zato_path` and edit the path back to 2.0.3

Now I'm running a copy of 2.0.3, even though 2.0.4 is installed according to the package manager.
