### ISSUE TITLE
Incorrect WSDL structure fixing

### ISSUE THREAD

**Issue by aleksb86** [zatosource/zato#451]
i.e. we have Zato service uses SOAP outgoing channel. Is it possible to add a some way to correct of corrupted WSDL in service class? This time is impossible to control how Zato makes a SOAP request. It would be good approaches like Suds`s 'doctor' and 'MessagePlugin'.

**Comment by dsuch** [comment]
Hi @aleksb86,

when you invoke an external SOAP resource you are given a SOAP client from suds to use but there is no automatic way to customize it using the tools you mentioned.

If you could provide a self-contained usage example of how it would work, it could be done for one of the future releases. But as of now, I'm sorry but there is no way to do it.

**Comment by dsuch** [comment]
However, another point is that you can build SOAP requests using lxml or other non-suds based tools, like here:

https://zato.io/docs/progguide/examples/soap.html#invoking-a-soap-service-no-wsdl

**Comment by aleksb86** [comment]
Thanks for fast reply.
