### ISSUE TITLE
Make Web-Admin access secure

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#452]
If you want to access the Web-Admin interface from remote, Django must be configured in a secure way.

I have already created a ticket for [documenting access via SSL](https://github.com/zatosource/zato-docs/issues/26).

But Django should also not run in debug mode which it does in Zato by default. I tried setting DEBUG=0 in web-admin.conf, but it didn't work since then the static files are not delivered any more - they must be delivered differently in production mode it seems (I don't know Django very well). This should be either properly documented or made the default.

**Comment by dsuch** [comment]
Hi @Cito - you are right and we need to update Django to a newer version + document how to make it serve behind TLS.

I'm adding both 2.0.6 and 2.1 labels to the ticket meaning that it will be done in 2.1 at the very latest but possibly will be available in an earlier release depending on how invasive it will need to be.

Thanks again!

**Comment by merwok** [comment]
An alternate setup is to not expose the admin port to the general internet, and allow only access from internal network.  For access from the outside, SSH port forwarding does the trick.

**Comment by Cito** [comment]
Sure, the admin page should only be accessible internally or via VPN. Still, there could be network sniffers even in the internal network. The admin page is extremely critical from a security point of view, so I would still want to use SSL.

**Comment by dsuch** [comment]
Judging by our settings.py and templates - do you think it should take a lot of effort to port web-admin to Django 1.8?

One thing I'm not clear about myself is ```django_openid_auth.auth.OpenIDBackend``` - has it seen any development in recent years.

But other than that?

**Comment by Cito** [comment]
Unfortunately I never really used Django. I prefer TurboGears and Pyramid.

If you ever want to redo the web-admin, I would recommend using something more lightweight like Flask, and use SQLAlchemy for the model instead of the Django ORM because you have that dependency anyway. But it would be probably much simpler to port it to the latest Django version.

**Comment by dsuch** [comment]
Thanks @Cito but I don't find Django heavyweight in the least so that's not a worry :-)

There will be a revamp at one point the next year to make it work better on mobiles but that's more about CSS and HTML anyway.

**Comment by dsuch** [comment]
Thanks everyone - I'm closing it in favour of #277 which will upgrade Django to current latest version.

**Comment by dsuch** [comment]
For reference - we are now migrated to Django 1.9.
