### ISSUE TITLE
add/remove servers to/from load balancer error

### ISSUE THREAD

**Issue by catroot** [zatosource/zato#453]
Removing a server from LB and further adding them causes server port to be 123456 instead of correct one (17010 in my case).
why?

**Comment by dsuch** [comment]
Hi @catroot,

the thing is, we don't know what the correct value is in the general case. It's precisely like you said, in your case it is 17010. But it doesn't have to be the case elsewhere.

Hence we deliberately use 123456 which is an invalid value that compels one to specify the correct value manually.

**Comment by catroot** [comment]
In this case there must be a field under the edit button to specify a proper address value for server in order to add/remove them without restarting a load balancer.
Or there a some way to gracefully reread config for LB?

**Comment by dsuch** [comment]
All restarts of the LB are always graceful and don't interrupt existing connections.

**Comment by catroot** [comment]
In my case, i have a flow of inbound connections, and when LB restarts, new connections cant be established. Lifetime of the single connection is very short. So, the meaning of the LB is getting lost without silent reconfiguration ability, because they have been designed to become unavailable for some time.

**Comment by dsuch** [comment]
Can you please describe step-by-step the scenario you are witnessing? What does it mean exactly that new connections cannot be established? How to reproduce the situation, precisely?

Thanks.

**Comment by catroot** [comment]
My service recieves an events from serveral sources. Inbound rate is about 15-20 requests per second.
when load balancer restarts (zato stop . && zato start . tooks about 20 seconds for me) - new connections cant be established with services untill load balancer becomes alive. Therefore, about 300 requests becomes rejected for LB restart time.
P.S. on my atom CPU an empty zato command tooks approximatelly 9 seconds to execute.
time zato --version
Zato 2.0.3.rev-281a9d29

real    0m9.921s
user    0m5.713s
sys     0m0.897s

**Comment by dsuch** [comment]
Ok, I see. But I'm not clear why you are restarting the load-balancer's process? You are right that when you do it, the whole process is stopped so there is nothing listening on the socket and no connections can be accepted.

If you'd like to update a load-balancer's configuration, you don't need to use ```zato stop/start``` - you should instead use this form https://zato.io/docs/web-admin/load-balancer/gui.html - clicking 'Validate and save' will restart it gracefully without interrupting ongoing connections.

**Comment by catroot** [comment]
So, that mean the "Validate and save" button is a reload LB button. I've got it. Thanks.

**Comment by dsuch** [comment]
Cool, in that case, I'll be closing the ticket. Feel free to re-open if needed.
