### ISSUE TITLE
Sample certificate has invalid hostname

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#455]
This is a test system which was installed with zato 2.0.3 and subsequently upgraded to 2.0.4, running under Ubuntu 14.04.

The problem: zato provides a test CA (good) and a server certificate signed by that CA (good), but the Common Name in the latter certificate is "Sample CA". Because it contains a space, it cannot possibly be a valid hostname, so not even putting stuff in `/etc/hosts` will make it work.

This can be demonstrated using curl (once SSL has been set up using the supplied certs):

~~~
$ curl --cacert /opt/zato/env/qs-1/load-balancer/config/repo/zato-lba-ca-certs.pem \
  --data-binary "<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><foo/></soap:Body></soap:Envelope>" \
  https://localhost:41223/nd1651/dummy
curl: (51) SSL: certificate subject name 'Sample CA' does not match target host name 'localhost'
~~~

or directly by looking at the certificate itself:

~~~
$ openssl x509 -in /opt/zato/env/qs-1/load-balancer/config/repo/zato-lba-cert.pem -noout -text | grep Subject:
        Subject: C=US, ST=My State, O=My Company, OU=zato-lb-agent, CN=Sample CA
~~~

Solution: for testing purposes, `CN=localhost` would be adequate. Alternatively the CN could be set to the system hostname.

**Comment by dsuch** [comment]
Fixed in 292334ea5bdafa710ffbe34c4e6144ec001e6967 - will be released in 2.0.5. It was a typo in the name of a variable used if common name is not provided on input:

```
default_ca_name = 'Sample CA'
default_common_name = 'localhost'
```
