### ISSUE TITLE
More documentation for Plain Outgoing connections.

### ISSUE THREAD

**Issue by thomasez** [zatosource/zato#458]
I am trying to use PUT and DELETE in a plain http connection and I cannot find it in the documentation. According to dsuch:#zato it exists but isn't documented.

Since he asked for a ticket as a reminder I'm creating one.

I would also like an example of using PUT with URL-variable and a payload (json) which I am not certain how to handle. Like a PUT  to /rest/v1/order/{id}

**Comment by dsuch** [comment]
Regarding a usage example - check it out here https://zato.io/docs/progguide/rest/outconns.html

Simply use .put instead of .post

**Comment by thomasez** [comment]
Verily true, the example was in the place I didn't look. (Been reading https://zato.io/docs/progguide/outconn/http.html

**Comment by dsuch** [comment]
@thomasez - do you think we can close it or would you still like for the docs to be extended?

**Comment by thomasez** [comment]
I would have added .put and .delete or mentioned ".[method]" somehow in https://zato.io/docs/progguide/outconn/http.html since it already has get and .post.

The example page you link to doesen't mention put or delete (or PATCH for that matter) either.

So yes, I still believe it would be wise to add some more to the doc about methods.

**Comment by dsuch** [comment]
Thanks, this is done now.

https://zato.io/docs/progguide/outconn/http.html#delete-options-put-patch
