### ISSUE TITLE
Error passing params ending in _id to outgoing http connections in 2.0.4

### ISSUE THREAD

**Issue by actodd** [zatosource/zato#460]
After upgrading to 2.0.4, all attempts to pass non-integer parameters to outgoing plain http connections with names ending in _id fail.

It appears the ESB is attempting to coerce them to ints automatically.

For example, a service that has a simpleIO of AsIs('order_id') will accept an order_id of "X12345" without difficulty.  When that service attempts to pass that parameter to an outgoing connection defined as http://some.machine/{order_id} it generates an error.

**Comment by dsuch** [comment]
Thanks, looking into it.

Any chance you could upgrade to 2.0.5 in the meantime? It brought back hotfixes to deal with such pressing cases without waiting for a full release.

**Comment by dsuch** [comment]
Hi @actodd - I check it out on 2.0.5 and could not reproduce it. This would be another reason to upgrade to the latest version. Thanks a lot.
