### ISSUE TITLE
Upgrade pyOpenSSL and requests

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#464]
Latest version of pyOpenSSL allows [SSL connection shutdown errors](https://github.com/pyca/pyopenssl/blob/master/ChangeLog#L64) to propagate properly. Please can you update:

* pyOpenSSL to 0.15.1
* cryptography to 0.7.2 or 0.9.1 (it is a dependency of pyOpenSSL, which now requires >=0.7.0)

In addition:

* updating requests to 2.7.0

would update the embedded urllib3 from 1.10.2 to 1.10.4, [resolving several bugs involving chunked transfer encoding and response framing](https://pypi.python.org/pypi/requests)

**Comment by dsuch** [comment]
Ok, added the 2.0.6 label.

**Comment by dsuch** [comment]
Done in 77ffdc20f1dbc7d0fdec2c1ec503c618eb886745 - will be included in 2.0.6.
