### ISSUE TITLE
Interval Based Scheduler not saving "repeats" argument

### ISSUE THREAD

**Issue by ivaano** [zatosource/zato#471]
invoking the service zato.scheduler.job.create doesn't store the repeats value in the odb

{  
   "cluster_id":1,
   "name":"ivan_test",
   "is_active":true,
   "job_type":"interval_based",
   "service":"test-scheduler",
   "start_date":"2015-08-22T22:55:41.710173",
   "repeats":3,
   "weeks":4
}

**Comment by dsuch** [comment]
Done in 398d80ce69575fc1e1f1db6cdca08bbb2e5bb29c - to be released in 2.0.6. Thank you @ivaano!
