### ISSUE TITLE
zato.service.get-deployment-info-list details not JSON

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato#476]
Hello,
when calling zato.service.get-deployment-info-list the details field is something like:

```python
"{u'remote_user': u'',
 u'current_host': u'A004T440\/A004T440.my.host',
 u'current_user': 'zato',
 u'timestamp': datetime.datetime(2015, 9, 22, 5, 4, 4, 332785),
 u'fs_location': '\/opt\/zato\/2.0.5\/zato-server\/src\/zato\/server\/service\/internal\/security\/apikey.pyc',
 u'object': <class 'zato.server.service.internal.security.apikey.Edit'>,
 u'remote_host': u'',
 u'method': u'service-store'}"
```

Which is not JSON (unlike stated in the [docs](https://zato.io/docs/public-api/details/zato.service.get-deployment-info-list.html)), it looks more like a str()'ified dictionary
I'm on Zato 2.0.5

**Comment by dsuch** [comment]
Thanks @pedrudehuere - this is done now!
