### ISSUE TITLE
Make it possible to inotify on multiple directories

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#483]
Right now we have only pickup-dir and it only listens to code.

We should support as many directories as users need it and the directories should not be limited to code only - we can use them to upload any data to services directly from the file system.

So, anything that got copied over to any such directory could be routed to one or more services that would process the file's contents.

**Comment by dj-xatra** [comment]
It would be nice if the files would be picked up in a predictable order, e.g. mtime or filename (or optionally either).

**Comment by dj-xatra** [comment]
Globbing would also be cool.
Use case: one of our applications insists on writing a useless index file with every useful file it writes. Something like Windows' thumbs.db, only it can't be turned off.

**Comment by dsuch** [comment]
Thanks @dj-xatra - yes, this all sounds good. I am thinking we could have something similar to what we do with OpenStack notifications in 2.0 though with FS notifications we would use inotify (or perhaps timers too as an option in case a given filesystem doesn't support notifications which I believe may be the case with some Windows shares):

https://zato.io/docs/web-admin/notif/cloud/openstack/swift.html

**Comment by dj-xatra** [comment]
Support for monitoring shared folders would be nice, but not essential because we could get around that by having applications copy to the Zato machine.

**Comment by dsuch** [comment]
All of this is done through pub/sub in #755. Thanks @dj-xatra !
