### ISSUE TITLE
Update to SQLAlchemy 1.0.9

### ISSUE THREAD

**Issue by merwok** [zatosource/zato#499]
SQLAlchemy released a 1.0 version that stabilizes the API and brings in bug fixes and perfomance improvements.  It would be nice to be able to use it.

**Comment by Tecktron** [comment]
It's been over a year now, any word on getting this updated? 
The current release is 1.1.5, that's quite a distance from 0.99....
would you accept a PR about it?

**Comment by dsuch** [comment]
Hi @Tecktron,

please send a PR but is there anything in particular that you need in SQLAlchemy 1.1.5?

If so, you can update the dependency yourself in versions.cfg and then run buildout without waiting for a new Zato release. Would you like for me to provide you with step-by-step instructions?

Regards.

**Comment by Tecktron** [comment]
Apart from the many bug fixes, the big one (for me) is PostgreSQL JSON support. There are other things as well, like the changes to other PostgreSQL "unhashable" types (specifically Array), the new indexable ORM extension, single-table inheritance, support for native Enum type, just to name a few.

I'll see what I can do about making these changes and getting a PR out. If the instructions are different than those [listed on the site](https://zato.io/docs/admin/guide/install/source.html), then I would appreciate that. 

Thanks

**Comment by dsuch** [comment]
Done.
