### ISSUE TITLE
Bug when delete service which listen to the channel or was scheduled.

### ISSUE THREAD

**Issue by Sukonnik-Illia** [zatosource/zato#506]
When service listens to channel and you delete this service, channel disappear from web interface but still works.
Same for scheduled jobs, if I delete service which was in scheduler, job disappear from web interface but KeyError messages begin to arrive in log.

**Comment by dsuch** [comment]
Hi @Sukonnik-Illia,

can you please clarify what you mean by "but still works"? How do you check it?

Thanks!

**Comment by Sukonnik-Illia** [comment]
* Upload Service

```
# -*- coding: utf-8 -*-
from zato.server.service.internal.helpers import Service


class test(Service):
    def handle(self):
        self.logger.warning('hello')
```

* Create channel:

name: test
URL path: /test
service: test.test
No security definition

* test it

```
requests.get('http://localhost:11223/test')
```
log message: 2016-01-04 15:32:31,037 - WARNING - 84:Dummy-352 - test.test:22 - hello

* delete service

* try to requests.get('http://localhost:11223/test')

```
ERROR - 85:Dummy-229 - zato.server.connection.http_soap.channel:22 - Caught an exception, cid:`K05Y9YGFRJD4MGNNR1NNCFHCC6AJ`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 337, in handle
    service = self.server.service_store.new_instance(channel_item.service_impl_name)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/store.py", line 79, in new_instance
    return self.services[class_name]['service_class']()
KeyError: u'test.test'
```

* Upload Service

* try to requests.get('http://localhost:11223/test')
```
WARNING - 84:Dummy-352 - test.test:22 - hello
```

**Comment by Sukonnik-Illia** [comment]
But no Plain HTTP channel with name 'test' in web interface

**Comment by pedrudehuere** [comment]
Don't know if it matters, but I think you should use 
`from zato.server.service import Service`

**Comment by lucval** [comment]
Did you forget to write or to execute the step where you delete/deactivate the test Plain HTTP channel?

**Comment by Sukonnik-Illia** [comment]
No I have not forgotten. Channel simply disappears

**Comment by Sukonnik-Illia** [comment]
After reloading servers phantom channels and scheduled jobs disappear.
But it would be nice to remove them with services, or add a notification when deleting services which listens to the channels.

**Comment by vabue** [comment]
> But it would be nice to remove them with services, or add a notification when deleting services which listens to the channels.

:+1:

**Comment by dsuch** [comment]
Thanks @Sukonnik-Illia - yes, this needs to be fixed indeed.

The correct behaviour would be:

* You delete a service
* Channel gets deleted too
* You invoke a service and receive 404 because there is no channel
* You upload a service
* You invoke a service and receive 404 again because there is no channel yet
* You create a channel
* You invoke a service and receive 200 now
