### ISSUE TITLE
haproxy does not log fatal errors anywhere

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#513]
In the standard quickstart cluster, if haproxy cannot start because of errors, this is silently ignored *and* the error is not logged anywhere.

Trying to start the service by itself:

~~~
cd cluster1/load-balancer
zato start .
~~~

returns "OK". `pidfile` is created but not `zato-lb-agent.pid`

All files in the `cluster1/load-balancer/logs` directory were zero bytes, except for `logs/lb-agent.log` but that contained only stale entries of the form:

~~~
2015-12-01 16:25:05,275 - INFO - 12478:MainThread - root:144 - Registering [<bound method LoadBalancerAgent._lb_agent_validate_save_source_code of
<zato.agent.load_balancer.server.LoadBalancerAgent object at 0x7f7499b421d0>>] under public name [validate_save_source_code]
~~~

In the end what I had to do to find the problem was to start haproxy manually at the command line, by copying the running command line from another cluster and removing `-D` (daemon) flag.

~~~
$ haproxy -f /opt/zato/cluster1/load-balancer/config/repo/zato.config -p /opt/zato/cluster1/load-balancer/zato-lb-agent.pid
[WARNING] 011/112255 (8144) : parsing [/opt/zato/cluster1/load-balancer/config/repo/zato.config:67] : a 'http-request' rule placed after a 'reqadd' rule will still be processed before.
[ALERT] 011/112255 (8144) : Proxy 'front_tls_optional_client_certs': unable to load CA file 'config/repo/zato-lba-ca-certs.pem' for bind '0.0.0.0:41223' at [/opt/zato/cluster1/load-balancer/config/repo/zato.config:69].
[WARNING] 011/112255 (8144) : Setting tune.ssl.default-dh-param to 1024 by default, if your workload permits it you should set it to at least 2048. Please set a value >= 1024 to make this warning disappear.
[ALERT] 011/112255 (8144) : Fatal errors found in configuration.
~~~

The issue here was CA file was mode 440 owned by root rather than zato, and after fixing this, haproxy started fine.

However, the fact that there was no logging caused an unnecessarily large outage while attempts were made to restart and debug the issue.

I believe it should be possible to reproduce this problem easily.

**Comment by dsuch** [comment]
Hi @candlerb - thanks for raising it, I understand the situation and it will be acted upon.

Just for reference - there is a dry run kind of functionality in web admin:

https://zato.io/docs/web-admin/load-balancer/source-code.html

You can upload new configuration and click 'Validate config' which will run HAProxy in config-checking mode without actually restarting it. This could have caught the misconfiguration with permissions.

**Comment by dsuch** [comment]
Hi @candlerb - the code to handle `zato start /path/to/load-balancer` and `zato start /path/to/load-balancer` has been extended and now haproxy runs in its dry-run mode prior to the load-balancer's being actually started.

I tested it with various configuration errors, including a valid certificate with incorrect permissions (your case) and now config errors are reported to console, such as here:

```
`command:[[u'haproxy', u'-c', u'-f', u'/tmp/zato-tmpYxQwop']], return code:[1], stdout:[], stderr:[[ALERT] 048/181535 (5677) : parsing [/tmp/zato-tmpYxQwop:56] : 'bind 127.0.0.1:11223' : unable to load SSL private key from PEM file '/tmp/cert.pem'.
[ALERT] 048/181535 (5677) : Error(s) found in configuration file : /tmp/zato-tmpYxQwop
[ALERT] 048/181535 (5677) : Proxy 'front_http_plain': no SSL certificate specified for bind '127.0.0.1:11223' at [/tmp/zato-tmpYxQwop:56] (use 'crt').
[ALERT] 048/181535 (5677) : Fatal errors found in configuration.
] 
`
    
$ echo $?
16
$
```
