### ISSUE TITLE
Adopt docker-compose and swarm for installation

### ISSUE THREAD

**Issue by allustin** [zatosource/zato#515]
zato is a composite application (i think)

thats why installation https://github.com/zatosource/zato/issues/new in distibuted env will be useful to run with docker-compose file

i have tried to create come gist for experiments https://gist.github.com/allustin/8b4308f29942369ef028

and if we have server clustering - will be useful to integrate it with docker swarm https://docs.docker.com/swarm/

**Comment by andy-wr** [comment]
Hi!
Thanks for the suggestion. We'll try to look deeper on Zato with Docker Swarm.

**Comment by kbni** [comment]
I decided to have another crack at getting Zato operational via Docker. I'm yet to test with Docker Swarm, but I've had some success running up a Zato cluster using this compose/Dockerfile collection:

https://github.com/kbni/docker-zato

I'm sure many improvements could be made to the Dockerfile, but there were a few challenges presented by Zato's architecture that made this trickier than it should be.

**Comment by allustin** [comment]
@kbni awesome. Portainer ?

**Comment by dsuch** [comment]
Closing in favour of #881.
