### ISSUE TITLE
basic auth with empty realm raises exception on basic-auth listing

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato#541]
When creating a basic-auth with an empty realm with the public API zato does not complain (it does complain if you try to do this in the web-admin).
After that, when listing the basic-auth definitions (public API or web admin) zato throws an error.

to reproduce:

    curl 'http://localhost:11223/zato/json/zato.security.basic-auth.create' --user pubapi:passwd -d '{"cluster_id":1, "name":"test_base_auth", "is_active":true, "username":"uname", "realm":""}'
    curl 'http://localhost:11223/zato/json/zato.security.basic-auth.get-list' --user pubapi:passwd -d '{"cluster_id":1}'

Cheers!

**Comment by pedrudehuere** [comment]
$ zato --version
    Zato 2.0.7.rev-dfee180c

**Comment by dsuch** [comment]
Thanks @pedrudehuere  - could you also please send logs snippets regarding this situation?

Each time you use the server API an entry with I/O is stored in an admin.log file in a server that processes your request. This also applies to actions performed in web-admin since web-admin uses server API itself.

So, can you please reproduce the situation but this time observing admin.log files and upload here the information that will be logged in these files for your requests?

Thanks a lot.

**Comment by pedrudehuere** [comment]
I set the log level of `zato_admin` to `DEBUG`, but I guess there's no debug log for it.
Here are the log entries when I create the basic auth definition (first CURL command above):

    2016-02-15 07:46:23,229 - INFO - 4571:Dummy-7 - zato_admin:22 - cid:[K06MTNP121G0RPW5ZZ8FEWWTZBMC], name:[zato.security.basic-auth.create], SIO request:[{u'username': u'uname', u'realm': u'', u'is_active': True, u'name': u'test_base_auth', u'cluster_id': 1}]
    2016-02-15 07:46:23,250 - INFO - 4571:Dummy-7 - zato_admin:22 - cid:[K06MTNP121G0RPW5ZZ8FEWWTZBMC], name:[zato.security.basic-auth.create], response:[{"zato_security_basic_auth_create_response": {"id": 64, "name": "test_base_auth"}}]

When I issue the command to retrieve the basic auth security definitions (second CURL command above) I get the following response:

    {"zato_env": {"details": 
    "Traceback (most recent call last):\n  File \"\/opt\/zato\/2.0.7\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", 
    line 198, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"\/opt\/zato\/2.0.7\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", 
    line 350, in handle\n    params_priority=channel_item.params_pri)\n  File \"\/opt\/zato\/2.0.7\/zato-server\/src\/zato\/server\/service\/__init__.py\", 
    line 429, in update_handle\n    raise resp_e\nZatoException: Expected elem:[realm] not found in item:[(['id', 'name', 'is_active', 'username', 'realm', 'password', 'sec_type', 'password_type'], (65, 'test_base_auth', True, 'uname', '', '0ff380e3b0f44452805113e18e887d23', 'basic_auth', None))]\n", 
    "result": "ZATO_ERROR", "cid": "K0403983P2RE43RWRR8233VJXGGY"}}

The generated log entry:

    2016-02-15 08:10:08,065 - INFO - 4699:Dummy-151 - zato_admin:22 - cid:[K0403983P2RE43RWRR8233VJXGGY], name:[zato.security.basic-auth.get-list], SIO request:[{u'cluster_id': 1}]


For completeness:
when creating the basic auth with no realm

    select * from sec_basic_auth;

gives an empty `realm` column, after updating it to a non-empty value the second CURL command runs OK

**Comment by dsuch** [comment]
Thanks @pedrudehuere - this situation is caught now and empty realms cannot be used anymore in API calls. Additionally you may want to subscribe to #569 that was opened to deal with it in a general case for the next major release.
