### ISSUE TITLE
Is there the JSON-RPC helper in zato?

### ISSUE THREAD

**Issue by viatoriche** [zatosource/zato#553]
I not found support for json-rpc, REST only.

If I want have a support for json-rpc, what I must do?
How can I write json-rpc outgoing connection and channel?
How can I use my json-rpc modules in Service?

**Comment by dsuch** [comment]
HTTP outgoing connections in Zato can be used to access any sort of resources. It does not matter if the underlying principles are based on REST, RPC or anything else.

Here is sample code showing how to call JSON-RPC endpoints using the 'request' module.

https://json-rpc.readthedocs.org/en/latest/quickstart.html

You need to go through Zato tutorial, learn how to use the basics, and then you will be able to call JSON-RPC using HTTP outgoing connections.

https://zato.io/docs/tutorial/01.html

Cheers.

**Comment by viatoriche** [comment]
@dsuch mmm, thx. Sounds as plan :cat:
