### ISSUE TITLE
postgres: zato zato localhost(48408) idle in transaction

### ISSUE THREAD

**Issue by viatoriche** [zatosource/zato#557]
Why? This "idle in transaction" may be many. Transactions does not close?

**Comment by dsuch** [comment]
Hi @viatoriche - I'm not sure what you mean? What is the context of the question? Thanks.

**Comment by viatoriche** [comment]
@dsuch Hi again

ps:

postgres 32746  0.0  0.2 2423372 20560 ?       Ss   15:16   0:00 postgres: zato zato localhost(52032) idle in transaction
postgres 32747  0.0  0.2 2423372 20624 ?       Ss   15:16   0:00 postgres: zato zato localhost(52034) idle in transaction
postgres 32750  0.0  0.2 2423292 20484 ?       Ss   15:16   0:00 postgres: zato zato localhost(52044) idle in transaction
postgres 32751  0.0  0.2 2423292 20432 ?       Ss   15:16   0:00 postgres: zato zato localhost(52046) idle in transaction

**Comment by dsuch** [comment]
Each Zato connection to PostgreSQL can be seeing in PostgreSQL using this query, column application_name:

```select * from pg_stat_activity;```

I am just not sure if you are worried about anything here? Is there anything in what you observe that indicates an issue?

**Comment by viatoriche** [comment]
7833+03 | 2016-02-10 15:16:10.158224+03 | f       | idle in transaction |             |              | SELECT service.id AS service_id, service.name AS service_name, service.is_active AS service_is_active, service.impl_name AS service_impl_name, service.is_internal AS serv
ice_is_internal, service.wsdl AS service_wsdl, service.wsdl_name AS service_wsdl_name, service.slow_threshold AS service_slow_threshold, service.cluster_id AS service_cluster_id

**Comment by dsuch** [comment]
Ok, you need to look at the ```state_change``` column too, this indicates when the connection was last time used.

When you start servers they open a few long-running connections through which you can then update a given cluster's objects, like outgoing connections or scheduler's jobs.

So it all looks OK. There are some connections open - you can note the value in state_change, then create a few objects and then delete them. You'll see that state_change is updated as these connections process your configuration change requests.

**Comment by viatoriche** [comment]
echo "select usename,state_change,state from pg_stat_activity where usename = 'zato' and state = 'idle in transaction';" | psql
 usename |         state_change          |        state        
---------+-------------------------------+---------------------
 zato    | 2016-02-10 15:16:10.152965+03 | idle in transaction
 zato    | 2016-02-10 15:16:09.243988+03 | idle in transaction
 zato    | 2016-02-10 15:16:50.384329+03 | idle in transaction
(3 rows)

$ date
Ср фев 10 15:52:38 MSK 2016

**Comment by dsuch** [comment]
Nice - since everything looks fine I will be closing the ticket now. Thanks!
