### ISSUE TITLE
Have the zato an REST or other API for configure

### ISSUE THREAD

**Issue by viatoriche** [zatosource/zato#558]
In my case: there is main global admin site for all system, where zato - subsystem (esb). We need integrate zato to our admin system.

**Comment by dsuch** [comment]
Hi @viatoriche - please tell me what the question is. I'm just not sure what it is based on your description in the ticket.

Thanks.

**Comment by viatoriche** [comment]
Hi @dsuch
Zato have a admin site, on this site user-admin can change any options, which save to DB (mysql, postgres or sqlite). Zato service get options from DB. How work with config DB without zato-admin? For example: REST or RPC API, SDK. Have the zato any API for change options?

**Comment by dsuch** [comment]
Yes, we have enmasse and admin API for it:

* https://zato.io/docs/admin/guide/enmasse.html
* https://zato.io/docs/public-api/intro.html

**Comment by viatoriche** [comment]
@dsuch Thx! I love zato more and more...
