### ISSUE TITLE
missing revision.txt

### ISSUE THREAD

**Issue by alirizakeles** [zatosource/zato#575]
revision.txt is missing in zato/code/.version.py on line 21

https://github.com/zatosource/zato/blob/main/code/.version.py#L21

When I try to install zato server via setup.py I got this error due to missing

``` bash
(zato)ali ~/dev/zato/code/zato-server (master) $  python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    execfile(_version_py, _locals)
  File "/Users/zops5/dev/zato/code/.version.py", line 21, in <module>
    revision = open(os.path.join(release_info_dir, 'revision.txt')).read()[:8]
IOError: [Errno 2] No such file or directory: u'/Users/zops5/dev/zato/code/release-info/revision.txt'
```

**Comment by dsuch** [comment]
Hi @alirizakeles,

it's not that it's missing - rather, zato-server is not meant to be installed under virtualenv using its setup.py - can you please tell me what you need it for?

Thanks.

**Comment by alirizakeles** [comment]
Hi @dsuch,

I was trying to figure out a way to create a development env for zato. I had a look buildout quickly, but i couldn't make it work. I dont know buildout and really do not add one more python thing unless it is an inevitableness.  I tried requirement.txt files with pip, but got many dependency errors etc. Lastly, I tried setup.py files. 

Thanks.

**Comment by dsuch** [comment]
Ok @alirizakeles - but it's not a coincidence that we are using buildout, in this kind of project it's superior to pip, virtualenv and any other Python build tool with the exception of conda, possibly.

Please tell me what you mean by 'creating a development env for zato' and I will guide you on how to best set it up.

Thanks a lot.

**Comment by alirizakeles** [comment]
@dsuch, I want to add some lines of code for zato, test them and more importantly use my favorite IDE. So I can import modules etc. and my IDE can inspect them.  

Also, I develop some zato services for my projects. I want my IDE to inspect imported zato modules and give me opportunity to use debug tools.

And I do not want to install them system wide, i use python virtualenvs per project to manage and isolate enviroments.

Thanks.

**Comment by dsuch** [comment]
Yes, I understand why you are using virtualenv, and in fact Zato uses virtualenv as well, it's just that virtualenv alone is not enough. Please find below information on how to achieve what you need.

1. If you are installing from source then you need to run `./install.sh` this is the main installation script.
2. If you are using a DEB or RPM then your binaries are installed to `/opt/zato/current`
3. No matter which method you use, you need to find the file called `./bin/py`
4. Execute this file - it's the main wrapper that adds all of Zato's dependencies to `sys.path`
5. Once it starts, run these commands:

```
$ from sys import path
$ ':'.join(sys.path)
```

6. This will give you all of the dependencies in the format that can be fed to your IDE.
7. I use it with Wing IDE - if you use a different IDE then you need to consult its documentation on how to append entries to PYTHONPATH
8. That is it, you will now have Zato  auto-completion, go-to-definition and so on.

Cheers.
