### ISSUE TITLE
How can I install zato from sources in any path?

### ISSUE THREAD

**Issue by viatoriche** [zatosource/zato#576]
subj

**Comment by dsuch** [comment]
Sorry @viatoriche - but what do you mean by `subj`? What is this ticket about?

**Comment by viatoriche** [comment]
@dsuch subj is subject: "How can I install zato from sources in any path?"

**Comment by viatoriche** [comment]
@dsuch Ok.

I did:

```
git clone git@github.com:zatosource/zato.git
cd zato
git checkout support/2.0
git pull
cd code
sudo ./install.sh
sudo chown viator. -R .
cd bin
source activate
Traceback (most recent call last):
  File "/home/viator/coding/zato/code/bin/zato", line 183, in <module>
    import zato.cli.zato_command
  File "/home/viator/coding/zato/code/zato-cli/src/zato/cli/__init__.py", line 27, in <module>
    from zato.cli import util as cli_util
  File "/home/viator/coding/zato/code/zato-cli/src/zato/cli/util.py", line 17, in <module>
    from zato.common.util import get_config, get_crypto_manager_from_server_config, get_odb_session_from_server_config, \
  File "/home/viator/coding/zato/code/zato-common/src/zato/common/util.py", line 43, in <module>
    from base32_crockford import encode2 as b32_crockford_encode
ImportError: cannot import name encode2

```

**Comment by dsuch** [comment]
Ok, thanks @viatoriche but please put some effort into it - you cannot expect people who spend their own free time to seriously treat tickets that read `subj` - I would not have even allowed it if your effort was covered by a commercial contract much less free support over GitHub.

Thanks.

**Comment by viatoriche** [comment]
@dsuch Ok. I just want test my code and code from sources, for contribute to zato are patches and features. I must know, how to install zato from sources

**Comment by dsuch** [comment]
Hello @viatoriche,

here is the information on how to install Zato from source code.

https://zato.io/docs/admin/guide/install/source.html

Best regards.

**Comment by viatoriche** [comment]
oh, thx @dsuch
