### ISSUE TITLE
Load balancer does not log

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#578]
In the default quickstart cluster, all the files in `load-balancer/logs/` are zero bytes except for `lb-agent.log`, which essentially is just startup information (registering services)

The specific issue is that if spurious requests are coming in, you can see events in serverX logs but you don't know the source IP address which sent them. The server http access logs show all connections from 127.0.0.1, i.e. coming from haproxy.

From googling, it may be that haproxy can't log to files; it can only log to syslog. But if so, why does `load-balancer/logs/http_access.log` even get created?

**Comment by dsuch** [comment]
Hi @candlerb,

http_access.log of each server can be configured to show the real client's IP - I will get back to you by the end of the week with details.

Could you please in the meantime post your load-balancer's configuration? In particular, I am thinking of the frontend stanza, the one which accepts incoming HTTP requests.

Thanks a lot.

**Comment by candlerb** [comment]
~~~
# ##############################################################################

global
    log 127.0.0.1:514 local0 debug # ZATO global:log
    stats socket /opt/zato/cluster1/load-balancer/haproxy-stat.sock # ZATO global:stats_socket
    ssl-default-bind-options no-sslv3

# ##############################################################################
~~~

Ah now I see: my local rsyslogd is running default config which only listens on `/dev/log`, not on UDP.

After enabling this in `/etc/rsyslog.conf`, I find `/var/log/haproxy.log` is created for incoming messages, due the the presence of `/etc/rsyslog.d/49-haproxy.conf`. Thank you!

(Aside: I have installed `haproxy 1.5.15-1ppa1~trusty` as this was necessary to get TLS to work)

**Comment by dsuch** [comment]
Closing - @candlerb please reopen if needed. Thanks :)
