### ISSUE TITLE
Option to stop stacktraces being returned to client

### ISSUE THREAD

**Issue by bw-aus** [zatosource/zato#592]
If a service has a bug, the response to the client is the zato_env structure which has a python stacktrace in the 'details' field.

There should be an option to stop this info from being returned in the response, because it gives away information about the code to the client.

I think a generic error message should be returned in the response, and the full stacktrace should just appear in the server logs.

**Comment by dsuch** [comment]
@bw-aus - yes, this makes sense and will be implemented for the next major release. Thanks for suggesting it!

**Comment by dsuch** [comment]
Done.
