### ISSUE TITLE
Whether it support working with zookeeper?

### ISSUE THREAD

**Issue by codepython** [zatosource/zato#662]
I think that will be a nice feature

**Comment by dsuch** [comment]
Hi @codepython,

please let me know what is required of a software package to be able to support ZooKeeper and I will be able to answer your question.

Thanks.

**Comment by dsuch** [comment]
Hi @codepython - I will close it for now since there has been no feedback for well over a month. But if you would like to discuss it, please just reopen the ticket. Thanks!
