### ISSUE TITLE
Impossible to create 2 basic auth definitions with same username.

### ISSUE THREAD

**Issue by ivaano** [zatosource/zato#663]
There is a Key constrain, composed of (cluster_id, username, sec_type) that impedes the creation of a new basic_auth definition with a username that is already defined but with a different password.

Lets say I have 3 external apis, all of them are using the same username (testuser), but each one of them with a different password (test1, test2, test3). I'll be unable to consume those apis until I ask the api owners from apis 2 and 3, to set the same password I'm using for api1 (test1).

**Comment by keith-phua** [comment]
To add on, the same username is also unable to be created under different clusters using the same ODB.

**Comment by FrankNagel** [comment]
In apikey security definitions the username column contains the HTTP header to use, i.e. you can't use the same header name for different API keys.
