### ISSUE TITLE
Service overview issues in web-admin for 2 identical cluster setup

### ISSUE THREAD

**Issue by keith-phua** [zatosource/zato#666]
I have setup 2 identical clusters under an external load-balancer for active-active HA.  These 2 cluster is setup under one OBD and each cluster connected to it's own redis.

We deploy the same service module in cluster 1 and 2.  Then we create in each cluster a http channel to expose the service. However we noticed that whenever we view the service overview, the service in cluster 1 will indicate "PLAIN HTTP: servicename,servicename" and in cluster 2, it will show "PLAIN HTTP: (NONE)".  Shouldn't the service overview in cluster2 be showing "PLAIN HTTP: servicename"?
This happen to all custom deployed services.  All internal services are showing it correctly in both cluster though.

I shutdown cluster1, My service in cluster2 still working and able to serve request even though it's showing "PLAIN HTTP: NONE".

**Comment by dsuch** [comment]
Hi @keith-phua - just as we spoke off-GitHub about it, this does not look correct and will be seen to. Thanks for opening the ticket!

**Comment by dsuch** [comment]
Hi @keith-phua - I am looking into it right now.

Just to confirm it - have you deployed your services to both clusters? Are you 100% certain? I understand you that you most likely have but I just need to double-check it.

Thanks.
