### ISSUE TITLE
Implement json-rpc like soap

### ISSUE THREAD

**Issue by lnoor** [zatosource/zato#667]
Beside soap support json-rpc [http://www.jsonrpc.org/](JSON RPC) version 2.
Perhaps using parts of tinyrpc [https://github.com/mbr/tinyrpc](Tinyrpc).

**Comment by dsuch** [comment]
Closing in favour of #937.

**Comment by lnoor** [comment]
No problem. Be advised though that Nextpertise is using json-rpc with zato as both client and server for over 2 years now. You may want to check with @teunis90 as I no longer work for Nextpertise.
