### ISSUE TITLE
Do not require cluster_id in API services if there is only one cluster in ODB

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#670]
Pretty much all of the [Zato API services](https://zato.io/docs/public-api/intro.html) require one to provide cluster_id on input.

This can be simplified in the most common case of there being only one cluster in ODB by making cluster_id optional. In this case, the cluster_id should be filled in automatically by Zato.

**Comment by kbni** [comment]
Would this be something that can extend to the web interface? (automatically select cluster 1, if only one cluster is there?)

**Comment by dsuch** [comment]
Hi @kbni,

yes, this is has been already implemented some time ago and in 3.x+ when you visit a web admin page and there is only one cluster this web admin instance has access to, then this cluster is automatically selected without a need to pick it and click submit.
