### ISSUE TITLE
HTTPSOAPWrapper sends JSON GET-requests with 'null' content

### ISSUE THREAD

**Issue by czintl** [zatosource/zato#671]
When sending a GET-request to an outgoing plain-HTTP Service, Zato sends the request with content. As "data" is set to "None" by default here
`def get(self, cid, params=None, *args, **kwargs):`
`self.http_request('GET', cid, None, params, *args, **kwargs)`

This then gets JSON-encoded to 'null' and sent with the GET-request (Content-Length: 4)
While this is allowed by the HTTP 1.1 specification, it can lead to problems with some Endpoints (e.g. SugarCRM REST API v10).
The quick fix for me was to change the line above to
`self.http_request('GET', cid, '', params, *args, **kwargs)`

I have read that e.g. Elasticsearch uses GET-Requests with data in the body, so it might even make sense to allow GET-Requests with data, but the default should be the empty string.

The same may apply to the other request-types with 'None' as data as well, but I haven't tested it.

**Comment by dsuch** [comment]
Thanks @czintl - this will be changed soon and '' (empty string) will be the default value.

**Comment by dsuch** [comment]
Done in 57287c5697f4a99c76a5dbc3ed2d07cee60ccbda - ported to main and support/2.0. Will be released in 2.0.8 and newer versions. Thanks @czintl!
