### ISSUE TITLE
Add call to super(Service, self).__init__() to Service.__init__()

### ISSUE THREAD

**Issue by lnoor** [zatosource/zato#694]
I have a lot of code that is shared between services. So I created a class and stored it in `zato_extra_path`. So far so good.

So now I define

```
class MyService(Service, MyClass):
    def __init__(self):
        super(MyService, self).__init__()
```

this does not call `MyClass.__init__()` as I expected because the Service class does not play along.

After appending `super(Service, self).__init__()` to `Service.__init__()` my **init**() method was being called. So please add this to the Service class.

For more info see: [super() considered super!](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/)

**Comment by csala** [comment]
@lnoor Why don't you just make your "MyClass" inherit from Service and make yourself the call to the Service.__init__ method there?

Doing so, your services will need to inherit only from "MyClass" and everything will work as you need it to.

**Comment by lnoor** [comment]
For this particular class that would work.
I just like to use multiple inheritance to combine otherwise unrelated hierarchies.
Like combining a Zato Service with a JSON-RPC library and I was trying to work out how to do that, but there is always more that one solution.
Nevertheless I think Zato should support multiple inheritance on a class like Service (stubborn, I know).
Thanks @csala

**Comment by csala** [comment]
I see your point @lnoor 
In my case, I once tried to use multi-inheritance in the same scenario (providing common functionality to all or part of my services), and at the end I ended up concluding that what I was trying to do was creating a particular type of Service, so direct inheritance made more sense.

But sure, it doesn't contradict your point that it would be good if Zato supported this development pattern out-of-the-box.
