### ISSUE TITLE
Make the inclusion of the SimpleIO.input_optional parameters in Service.request.input configurable

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#696]
SimpleIO has a property `input_optional`. When a service is called without these parameters they get a default value. It would be nice if it is possible to leave these parameters out of of `Service.request.input` when the parameters are not available in the incoming request. Because atm. it is impossible to discriminate between these two situations:
-  parameter is not in the input and get default value
-  parameter was in the input, and the value is the same as the default value

It would be nice to make this behaviour configurable.

**Comment by dsuch** [comment]
I'm working on a few changes to SimpleIO right now - could you please prepare an example of it in terms of actual JSON documents and SIO definitions?

Thanks.
