### ISSUE TITLE
Cron-style job editing fails

### ISSUE THREAD

**Issue by bw-aus** [zatosource/zato#697]
I am seeing a problem with the scheduler, after editing cron-style jobs via the web-gui.

The scheduler.log, when executing the edited job, gives a log line like this:

```
2016-07-19 04:00:00,935 - INFO - 2014:Dummy-58694 - zato_scheduler:22 - Job executed `my description here`, `{u'name': u'my description here', ...SNIP..., u'cron_definition': None, ...SNIP..., u'type': u'cron_style', u'id': 1035L}
```

Note that **cron_definition** above is **None**, which is wrong. This job also incorrectly executes at the old time/date, i.e. the 'edit' operation has seemingly failed.

If I restart the zato servers then the new time/date works, and the log messages are correct.

I believe the problem is with the code in `zato-common/src/zato/common/scheduler.py`, in the `Job` class.

When a job is edited it is unscheduled then created again from a clone of the job. However, the clone method doesn't seem to pass the **cron_definition** on to the newly cloned job.

```
class Job(object):
    def __init__(self, id, name, type, interval, start_time=None, callback=None, cb_kwargs=None, max_repeats=None,
            on_max_repeats_reached_cb=None, is_active=True, clone_start_time=False, cron_definition=None):
```

...SNIP...

```
    def clone(self):
        return Job(self.id, self.name, self.type, self.interval, self.start_time, self.callback, self.cb_kwargs, self.max_repeats,
            self.on_max_repeats_reached_cb, self.is_active, True)
```

The clone method above does not seem to include **cron_definition** in the kwargs of its instantiation of Job.

**Comment by dsuch** [comment]
Adding 2.0.8 label as it should be ported to 2.0.x for sure. Thanks @bw-aus.

**Comment by dsuch** [comment]
Done in 006c1cc3c62f9b7c8f9c50b7c75d8b6fa6fd34d1 - thank you @bw-aus !
