### ISSUE TITLE
Administrate Pub/Sub with REST HTTP

### ISSUE THREAD

**Issue by xxbillouxx** [zatosource/zato#715]
Like REST for producers and consumers: is it possible to expose REST for :
- topic creation
- topic deletion
...
?

Thanks a lot !

**Comment by dsuch** [comment]
Yes, 99.99% of what web-admin does can be done with public API. In this case there is simply no documentation for it but services are here:

https://github.com/zatosource/zato/blob/main/code/zato-server/src/zato/server/service/internal/pubsub/topics.py

In general, web-admin is just a client of the server API, it does not modify server databases directly. So almost anything that you can do in web-admin can be done by your own tools.

**Comment by xxbillouxx** [comment]
Thank you.

How the class _Create(AdminService)_   (in topics.py) is matched to an URL ?

I cannot find the URL to use...

For this case ("create a topic"), can you explain how I can find the right URL(and params) ?

Thank you :)

**Comment by xxbillouxx** [comment]
When I try :

_curl -X POST -H "Content-Type: application/json" -d '{"topic":"topic1", "msg":"message"}' http://crm:crm@127.0.0.1:11223/zato/pubsub/topic/create/_

I have the message :
_You are not authorized to access this resource_

:(

**Comment by dsuch** [comment]
Can you please contact me on dsuch@zato.io? I'm not really sure what your email is. Thanks!

**Comment by xxbillouxx** [comment]
Done ;)
