### ISSUE TITLE
PubSub consumers subscribing to several topics at the same time get wrongly routed messages

### ISSUE THREAD

**Issue by FrankNagel** [zatosource/zato#717]
Assume you have two topics T1 and T2 and one consumer C1. C1 is defined as a consumer for both T1 and T2. Now publish two messages on T1 and T2, respectively. Both messages will end up in only one of the two defined receiving queues.

In the function [move_to_target_queues](https://github.com/zatosource/zato/blob/a3cf95e349480404bf3f876c5e736b057b6cc701/code/zato-common/src/zato/common/pubsub/__init__.py#L704) you use `topic_to_cons` followed by `cons_to_sub` to retrieve the relevant subkeys. This strategy is not valid in the scenario above.

**Comment by dsuch** [comment]
Hmm.. so instead of a total of four messages going two to both topics there are two messages going to one topic only?

**Comment by FrankNagel** [comment]
No, you don't lose any messages. My wording was not clear enough. If you publish a message M1 to T1 and M2 to T2, both messages will end up in one of the receiving queues for C1

**Comment by dsuch** [comment]
Ok, I see. Does this happen only if both M1 and M2 are published within the same invocation of move_to_target_queues? This method is by default executed once in 3 seconds.

Say you publish M1 now and M2 after 5 seconds. Will it be fine after 5 seconds?

**Comment by FrankNagel** [comment]
Timing does not matter. Consistently the same receiving queue gets all the messages for topics C1 is subscribed to. In the example, I only used two messages in the example because I don't know beforehand which one will be misrouted. The same happens with only one message moving through the system if I publish to the wrong topic.

**Comment by dsuch** [comment]
@FrankNagel - I thank you a lot for the ticket but I am closing it in favour of #755, which adds new pub/sub mechanism that will deal with this question while providing dozens of new features in 3.0. Regards.
