### ISSUE TITLE
Allow file inclusion in service-sources.txt

### ISSUE THREAD

**Issue by lnoor** [zatosource/zato#722]
The comment in service-sources.txt advises to add services halfway through the file.
I suggest a possibility to keep my own services in a separate file that is included in service-sources.txt, perhaps in the form of a glob pattern.

**Comment by lnoor** [comment]
Thinking a bit more about it.
It is even nicer if in server.conf the key 'service_sources' would accept a list of files instead of a single file. It is probably also less work to implement and achieves the same goal: separate lists of system and application services that should be deployed.

**Comment by dsuch** [comment]
Yes, this is indeed how it was about to be implemented like. Will be definitely easier to do it in this manner.
