### ISSUE TITLE
bug: Exception when using an API KEY authentication.

### ISSUE THREAD

**Issue by lnoor** [zatosource/zato#727]
Using Zato version: **Zato 3.0.0pre1.rev-d25de71c**

I have a service protected by "Delegated to RBAC" using API KEY authentication.
When trying to access the service the following exception message is produced in the logfile.

> 2017-01-05 10:51:20,086 - ^[[1;31mERROR^[[0m - 21503:DummyThread-3381 - zato.server.connection.http_soap.channel:252 - Caught an exception, cid:`40786233996c5f8fb97a1e67`, status_code:`500`, _format_exc:`Traceback (most recent call last):
>   File "/opt/zato/3.0.0/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
>     sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
>   File "/opt/zato/3.0.0/zato-server/src/zato/server/connection/http_soap/url_data.py", line 684, in check_security
>     sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
>   File "/opt/zato/3.0.0/zato-server/src/zato/server/connection/http_soap/url_data.py", line 665, in check_rbac_delegated_security
>     sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store, False)
>   File "/opt/zato/3.0.0/zato-server/src/zato/server/connection/http_soap/url_data.py", line 701, in check_security
>     self.enrich_with_sec_data(wsgi_environ, sec_def, sec_def_type)
>   File "/opt/zato/3.0.0/zato-server/src/zato/server/connection/http_soap/url_data.py", line 196, in enrich_with_sec_data
>     data_dict['zato.sec_def']['id'] = sec_def['id']
> KeyError: u'id'
> `

The same service accessed using HTTP Basic Auth works as expected.

**Comment by dsuch** [comment]
Would you please have a look at 60d5d6aef7a2a4a5c918ab9d671e3e9f697f7567? It contains a few API keys-related fixes and I tested everything with both RBAC delegated as well as with regular API keys security definitions.

**Comment by lnoor** [comment]
I built and installed version 3.0.0rc1+rev.d0f13586.
I couldn't upgrade the sqlite database so I had to install a new quickstart environment on my dev system.

'Delegating to RBAC' doesn't work at all.
Directly using API authentication didn't work.
Directly using HTTP authentication failed on some accounts.
I will try to email you my test procedure and logs later today after (triple) verifying the procedure.

**Comment by dsuch** [comment]
Right, I can see an issue with API keys but not with Basic Auth so please provide details about the latter. 

A provisional workaround for the former is to restart the server after creating a definition but a full resolution will be ready within about 12 hours.

**Comment by lnoor** [comment]
After verifying the zato config and restarting zato I tried to create useful log files.
However, now everything appears to be working.
Therefore I will close the ticket.

**Comment by dsuch** [comment]
Thanks @lnoor but I pushed commit 75d7de1230ac6d079927efb91163925d6bf70986 anyway because restarts should not be required for API keys to work.
