### ISSUE TITLE
Add option to suppress stack trace on exception

### ISSUE THREAD

**Issue by lnoor** [zatosource/zato#728]
When encountering an exception Zato now produces a stack trace.
Add an option to suppress this on the production environment.

I remember seeing this request before somewhere but I cannot find it anymore.

**Comment by dsuch** [comment]
Hi @lnoor,

this was actually already done in ticket #710 - but it's just not been ported to 3.x yet.

**Comment by lnoor** [comment]
Ok, as this is a duplicate of an open ticket, I'm closing this ticket.

**Comment by dsuch** [comment]
#710 was ported to main in commit defa8a0ddeefd162c695699a1f22a26986c7b49f. Thanks @lnoor !
