### ISSUE TITLE
scheduler missing and Zato throws Error after service removed via Web

### ISSUE THREAD

**Issue by raybog** [zatosource/zato#757]
I have removed a service vie Web Admin console. After that the scheduler, that was invoking removed service, disappeared  from the Web Admin. However by inspecting the logs the scheduler is still running and throwing an error about missing service.

**Comment by dsuch** [comment]
Hello @raybog,

please send in the relevant parts of admin.log, server.log and scheduler.log from the servers (not web-admin).

However, do not send the whole files, only the bits that are related to the scenario that you are describing from its beginning to end.

Regards.

**Comment by dsuch** [comment]
Thanks for the ticket @raybog - I will be closing it due to inactivity. If it is still needed, please reopen with details.
