### ISSUE TITLE
AWS S3 Proxy URL

### ISSUE THREAD

**Issue by xsetra** [zatosource/zato#781]
No amazon S3 proxy URL support, could be better.
Boto S3 connection parameters :
http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.connection.S3Connection

**Comment by dsuch** [comment]
Hi @xsetra,

yes, this is not possible today - would you like to contribute a PR basing on what we already have?

**Comment by xsetra** [comment]
Hi Dariusz,

I couldn't set up development enviroment. Can you share documentation for that. Thanks.

**Comment by dsuch** [comment]
Closing old tickets.
