### ISSUE TITLE
Make JWT API services conform to documentation

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#785]
According to the specification, responses should not include the Zato admin envelope yet it is returned.

https://zato.io/docs/public-api/details/zato.security.jwt.log-in.html
https://zato.io/docs/public-api/details/zato.security.jwt.log-out.html

**Comment by yishenggudou** [comment]
这个项目 思路蛮好的, 想问下作者现在还在维护吗

**Comment by dsuch** [comment]
Done in ce62f067560ce90da28e2a67edd19e2f119e2160.
