### ISSUE TITLE
Patch suds cache in /tmp

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#794]
Right now suds keeps its cache in /tmp/cache directory - this works as long as all Zato servers in a given system run under the same OS user.

However, in some installations there will be multiple Zato environments running under different OS users, for instance different test environments.

This is why suds should be patched to keep the cache in /tmp/{os_user}-suds, e.g. /tmp/zato1-suds or /tmp/zato2-suds.

All of this is taking place in suds/cache.py:

https://bitbucket.org/dsuch/suds/src/fb304981931beda9a3fac24aa7c19b5c0f83430e/suds/cache.py?at=default&fileviewer=file-view-default#cache.py-114

**Comment by jjmurre** [comment]
I made a pull request to suds. Now every Suds Client has its own cache. For Zato this means that every outgoing connection has a unique cache. And every work duplicates the number of connections. So, this can lead to a lot of caches. Maybe this could by optimized by using the Zato cluster name for generating a suds cache directory name. But, that needs more plumbing in Suds and also in Zato.

I bumped the version of Suds to "0.6.1 (development)". Not sure about the naming conventions for Suds.

Pull request: https://bitbucket.org/dsuch/suds/pull-requests/1/make-directory-name-for-cache-unique/diff

**Comment by dsuch** [comment]
Thanks @jjmurre - I merged the PR from BitBucket though this is still not the final form because, like you said, this now adds a lot more of caches. Ultimately, I think there should be a cache for each Zato server separately. But I believe we can close the ticket until we decide that it is truly needed.
