### ISSUE TITLE
Cannot talk to site with sha384WithRSAEncryption certificate

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#796]
The version of requests and/or urllib3 and/or pyOpenSSL bundled with zato 2.0.8 cannot communicate with a site where the [intermediate certificate](https://support.comodo.com/index.php?/Knowledgebase/Article/View/968/108/intermediate-ca-2-comodo-rsa-organization-validation-secure-server-ca-sha-2) uses `sha384WithRSAEncryption`

A fresh python virtualenv is able to talk to this site with the following requirements:

~~~
requests==2.18.4
pyOpenSSL==17.3.0
urllib3[secure]==1.22
# https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
~~~

(zato 2.0.8 bundles requests 2.7.0, pyOpenSSL 0.15.1, urllib3 1.10.4)

Temporary but insecure workaround: disable certificate validation with `verify: False`

**Comment by dsuch** [comment]
Thanks @candlerb - this would be probably an OpenSSL-level exception, right? Can you send it in?

**Comment by candlerb** [comment]
The error from the code running inside zato was `SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]`

I was able to replicate this inside a virtualenv pinned to the same library versions that zato uses, and got the same error:

~~~
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.request(data="", method="POST", url="https://<snip>/", verify=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/src/cfflow/venv/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/src/cfflow/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/src/cfflow/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/src/cfflow/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
>>> 
~~~

In a venv with the newer libraries, the connection works.

I cannot say for sure that the `sha384WithRSAEncryption` is the exact cause of the problem.  However the problem only occurred after the target site renewed their certificate, and the new chain includes the Comodo certificate with `sha384WithRSAEncryption`, so this seems likely.

In any case, it's something about the site which requires newer versions of those libraries to work.

Unfortunately the site in question is a private API and is IP-wrapped, so I can't give you the actual URL to talk to.

**Comment by dsuch** [comment]
Hi @candlerb,

can you update dependencies in versions.cfg directly in your environment?

Otherwise, this will have to wait after 3.0 is released - we are nearing it now and there is practically very little time left for matters other than 3.0 development or commercial support.

I'll add 3.0 milestone to this ticket though to make sure that the dependencies you listed see upgrades for 3.0.

Thanks.

**Comment by candlerb** [comment]
I tried a full rebuilt of zato with updated `versions.cfg` but it got tied into knots, I don't have the exact errors unfortunately.  It will wait.

**Comment by dsuch** [comment]
OK, I see - thanks a lot. Yes, updating dependencies is a rather time-consuming process that I have to go through each time anything substantial changes.

But without having fixed versions as in versions.cfg it would be all unmanageable, everyone would run on different version of each of them.
