### ISSUE TITLE
How to install the package zato-server

### ISSUE THREAD

**Issue by dxj1113** [zatosource/zato#802]
When I install the package zato-server by use the setup.py.
The error message shows as below

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    execfile(_version_py, _locals)
  File "D:\gitcode\zato\code\.version.py", line 21, in <module>
    revision = open(os.path.join(release_info_dir, 'revision.txt')).read()[:8]
IOError: [Errno 2] No such file or directory: u'D:\\gitcode\\zato\\code\\release
-info\\revision.txt'
```

**Comment by dsuch** [comment]
Hello @dxj1113,

as things stand today, we do not support installation of individual components with pip. We also do not support Windows yet.

If you'd like to install Zato from source, please follow the instructions here:

https://zato.io/docs/admin/guide/install/source.html

Thanks.

**Comment by dxj1113** [comment]
@dsuch Thank you
