### ISSUE TITLE
config bunches don't convert string to boolean where appropriate.

### ISSUE THREAD

**Issue by dw** [zatosource/zato#824]
For example, the key "self.fs_server_config.component_enabled.websphere_mq" is string "False", however in code tests such as https://github.com/zatosource/zato/blob/main/code/zato-server/src/zato/server/base/parallel/__init__.py#L468 , it is always treated like a boolean truthiness test.

That means all those component_enabled tests always evaluate to true.

Uncovered it by accident while trying to fix something else.

**Comment by dsuch** [comment]
Thanks for catching it - fixed in 41d4423ff242429619016040326c0e4f3a286339.
