### ISSUE TITLE
pip.download errors on main

### ISSUE THREAD

**Issue by DickKnol** [zatosource/zato#834]
On main branch when installing from source (on Ubuntu), pip 10.0.1 is installed. Zato is incompatible with this version. 

There are two solutions for this issue: 
- Ensure Zato is compatible with pip 10 
   - the problem seems to be with `zato-common/src/zato/common/util/__init__.py`, which uses pip.
- Adjust installer to install pip 9.

**Comment by dsuch** [comment]
Hi @DickKnol - can you tell me what Ubuntu version it is? Thanks.

**Comment by jjmurre** [comment]
I ran into the same issue with pip 10. 

"... trying to use an internal, implementation detail of pip which is not a supported way of using pip. pip 10 made this explicit by moving almost all of it into pip._internal namespace."

From: https://github.com/pypa/pip/issues/5272

**Comment by dsuch** [comment]
@jjmurre @DickKnol - will you be please able to send a PR for it?

This is a simple change really, zato.common.util imports pip.download to be used in function decompress in the same module.

That function is used in zato.server.service.store.ServiceStore.decompress to unpack an archive of services to be deployed - which is an undocumented feature that will have to be rewritten anyway so it too can be safely removed.

Thanks.
