### ISSUE TITLE
Initial deployment of channels with enmasse does not work

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#854]
For development and testing I use a docker image with a zato instance.

I am running 1 Zato server in the foreground (to see logging).
The services that I need, are hotdeployed.
The channels that I need, are added using "enmasse".
The problem is that the channels are not working correctly, when I deploy them with enmasse.

If I go to the web-admin and open+save the channels, the channel are working correctly.
The enmasse command I use:
zato enmasse server1 --input zato-import.json --import --replace-odb-objects

Also re-running the enmasse command (so updating the channel definitions) solves the problem.

This problem still persists in Zato 3.

**Comment by dsuch** [comment]
Can you send me a sample channel definition that exhibits it? Naturally, I will use a different service name. Thanks.

**Comment by jjmurre** [comment]
I'll send you a channel definition through e-mail, because I do not want to expose this info on github, it is an internal project.

**Comment by dsuch** [comment]
One question - can you tell me what you mean by 'channels are not working correctly'? Thanks.

**Comment by jjmurre** [comment]
After running enmasse for the first time, channels do not work.
We are having this setup of our SimpleIO inner class inside the service.

    class SimpleIO:
        input_required = ('organisation_id', )

When reading this value:
            getattr(sio, 'input_optional', ())

We are not getting our provide parameters but we are getting the value we configured for 'UNKNOWN'.

However, after we have updated the same channels with enmasse, it is working correctly.

**Comment by dsuch** [comment]
Just to be doubly sure, you only run enmasse and it is not combined with service deployment? I.e. you are sure this is not a re-deployment of services that is actually fixing it, you are positive it is enmasse?

**Comment by jjmurre** [comment]
Yes, I just replayed the whole process.
Start zato
Hot deploy services
Load channels with enmasse
-> failure to get url parameter
(tried to hot deploy services again, that does not help)
Reload channels with enmasse (so using --replace-odb-objects)
-> success to get url parameter

**Comment by dsuch** [comment]
I'm trying to reproduce it - is it correct to say that this only happens if this parameter is part of the URL path in a REST channel, e.g. /get/{organisation_id} ?

**Comment by jjmurre** [comment]
Yes, that is correct.
