### ISSUE TITLE
New Zato 3 scheduler component creation needs more documentation

### ISSUE THREAD

**Issue by rtrind** [zatosource/zato#860]
Please add page referring to the new scheduler component, in https://zato.io/docs/admin/guide/install-config/overview.html and subsequent pages.

**Comment by dsuch** [comment]
Here is new content:

https://zato.io/docs/3.0/admin/guide/install-config/install-scheduler.html
https://zato.io/docs/3.0/admin/guide/install-config/config-scheduler.html
https://zato.io/docs/3.0/admin/cli/create-scheduler.html

I will be updating the architecture pages too.
