### ISSUE TITLE
Zato 3 scheduler configuration does not contemplate the usage of Redis Sentinel

### ISSUE THREAD

**Issue by rtrind** [zatosource/zato#863]
Since I used sentinel for the regular servers, I think the new scheduler component will have some problems when dealing with read-only nodes, so the same logic applied to the server component should be applied here.

Please evaluate.

**Comment by dsuch** [comment]
Thanks for spotting it. Schedulers use the same underlying Redis client as servers do so you can for sure use sentinels.

If you open scheduler.conf and add the following to the **[broker]** section ..

```
socket_timeout=
charset=
errors=
use_redis_sentinels=False
redis_sentinels=
redis_sentinels_master=
shadow_password_in_logs=True
log_connection_info_sleep_time=5 # In seconds
```

.. you will have obtained the same configuration as servers use. 

I also pushed a changeset to include this in all newly created scheduler instances.
