### ISSUE TITLE
 Support for SSO via OpenID Connect 3rd Party Authentication Providers

### ISSUE THREAD

**Issue by techdragon** [zatosource/zato#868]
The new SSO support doesn't appear to follow any sort of interoperability standard (if it does, I did not find mention of it). There should be support for using an existing Single Sign On standard such as SAML or OpenID Connect.

I'd like to see support for using 3rd Party OpenID Connect Providers (Such as Auth0.com, RedHat's Keycloak, and WSO2 Identity Server) built into Zato.

**Comment by dsuch** [comment]
Support for SAML interoperability, or other protocols, is planned, though there are no plans to implement it at this time.

If you would like to see any features included in Zato, please feel free to contact me on dsuch@zato.io to discuss terms of commercial support under which such extensions can be created.

Regards.

**Comment by jcmcken** [comment]
Is it possible to authenticate ESB users via headers or session environment variables? E.g. [here's](https://docs.djangoproject.com/en/2.1/howto/auth-remote-user/) an example in Django showing how to do this.

We use this pattern a lot. You front your services with an authenticating proxy (implementing arbitrary schemes, e.g. SAML or OIDC), and you configure the backend to trust the ``REMOTE_USER`` environment variable or header
