### ISSUE TITLE
Debug of services

### ISSUE THREAD

**Issue by jpoa** [zatosource/zato#869]
Greetings!

I am looking at possibilities of doing some debug of the services while developing them. I saw some commits in GitHub about a web based debugger, I am also looking at integrating PyCharm, Docker and Zato for debugging.

Any pointers / ideas for this? I can link the interpreter of Zato running inside a container to PyCharm, but I could use some ideas for the service debugging.

**Comment by dsuch** [comment]
Hello @jpoa,

the web-based debugger is not something that is already implemented - in fact, I wonder myself if it should not wait until we support Python 3 which makes such things easier to achieve ([PEP 523](https://www.python.org/dev/peps/pep-0523/)).

As for connecting Zato to PyCharm for debugging - I would like to see it myself. Are there any generic guidelines that PyCharm offers in that regards? Can you treat it as simply connecting to a remote Python process that a Zato server is?

**Comment by jpoa** [comment]
For some reason I missed the update on this issue and thought you were having a break.

"Can you treat it as simply connecting to a remote Python process that a Zato server is?"
In a general way it might, I could run a python interpreter (with debug) inside a container with PyCharm. The IDE also mounts a local folder inside the container via mount (and this is what is executed).
So the supporting services like Redis can be included in the image and the zato code itself is then mounted in the container and executed via PyCharm.

I think it is possible. My problem at the moment is understanding which processes need to be started to successfully debug a service and where to place the code for the mentioned service.

Is there a location where the services end up that would allow to define the breakpoints? I tried to find something on the documentation with no success.

**Comment by dsuch** [comment]
The best way to know what process to attach to is to start one server only and to start it in foreground, e.g.

```
$ zato start /path/to/server --fg
```

This will yield information such as 'Booting worker with pid: 4025' - this is the PID that you can attach to. Incidentally, this will also let you stop that server with Ctrl-C which is very convenient during development.

As for placing the code, I'm not sure I fully understand the question, do you mean the location in the filesystem from which a service is read when a server starts up?

**Comment by jpoa** [comment]
Yes, or more precisely, the location in the file system from which a service is executed by the server.

Is there a place where the server copies the .py files? I am asking so that I can define the breakpoints there.

**Comment by dsuch** [comment]
After you list services in web-admin, click the name of the one that you need which will lead you to the Overview section. One of the tables is **Deployment info** and the service's location on each server is under **fs_location** key, e.g. /opt/zato/server1/work/hot-deploy/current/myservice.py.

This location can be configured in server.conf via **hot_deploy.work_dir** entry.

**Comment by dsuch** [comment]
I am closing the ticket due to inactivity but just for the reference, some time ago a user in the forum shared a way to debug services from command line, here it is:

https://forum.zato.io/t/interactive-pdb-prompt-with-zato-server-fg-does-not-work-anymore-in-zato-3-debugger/1745/3?u=forum-admin
