### ISSUE TITLE
Add parameters in URL path to self.request.http.path

### ISSUE THREAD

**Issue by jsabater** [zatosource/zato#875]
When not using SimpleIO to create a service, it would be convenient to be able to access parameters in the path via self.request.http. For example:

```
# Channel /app/customers/{id}/invoices/{id}/payments
# Get a customer, an invoice and all payments/receipts of the invoice
class GetCustomerInvoiceWithPayments(Service):
    def handle(self):
        customer_id = self.request.http.path[0]
        invoice_id = self.request.http.path[1]
```

Or a similar way (haven't checked how currently Zato internally handles the parameters in the path when using SimpleIO).

Parameters in the query string would still be accessed through something like this:

`qs = parse_qs(self.wsgi_environ[‘QUERY_STRING’])`

Also please add documentation and coding examples when using `self.request.http`

**Comment by dsuch** [comment]
This is done, you can install it with the [latest updates](https://zato.io/docs/admin/guide/install/update.html).

Two new attributes are:

* self.request.http.path # Path only
* self.request.http.params # All parameters, including from query string

For instance, if URL path in a REST channel is '/{user_id}/{user_type}', then:

$ curl localhost:11223/778899/admin

.. will you give you access to attributes via self.request.http.params and self.request.http.path will be '/778899/admin'.

The 'params' attribute supports both dotted notion and dict-like access, i.e. all of this will work:

* self.request.http.params.user_id
* self.request.http.params['user_id']
* self.request.http.params.keys()
* self.request.http.params.items()

If there are conflicts between path and query string parameters, they are resolved per channel's definition, QS over path vs. Path over QS.

I will update the documentation along with other topics from ticket #876.

**Comment by dsuch** [comment]
Just for reference, to access GET and POST data, one uses:

* self.request.http.GET
* self.request.http.POST

They are dict-like objects with attribute access as well, e.g. self.request.http.GET.myparam or self.request.http.GET['myparam'].

**Comment by dsuch** [comment]
Closing.
