### ISSUE TITLE
Match HTTP request to HTTP verb configured in channel

### ISSUE THREAD

**Issue by jsabater** [zatosource/zato#877]
Currently, HTTP requests are matched against the URL path configured in the channel, not taking the HTTP verb into consideration. This prevents the developer from designing/implementing a REST API with the following behaviour:

- GET /app/users to get a list/collection of users.
- GET /app/users/{id} to get a user.
- DELETE /app/users/{id} to delete a user.
- PUT /app/users/{id} to update/modify a user.
- POST /app/users to create a new user.
- GET /app/users/{id}/roles to get the list of roles of a user.
- DELETE /app/users/{id}/roles/{id} to delete a role of a user.
- Etcetera.

Please modify Zato so that the HTTP VERB is taken into consideration when matching the channel to the HTTP request.

Thanks in advance.

**Comment by dsuch** [comment]
This is done:

https://zato.io/blog/posts/http-accept-method-headers.html

**Comment by jsabater** [comment]
Brilliant feature! Keep up the good work! :-)
