### ISSUE TITLE
Exchange Types in Zato Pub/Sub with AMPQ ... RabbitMQ

### ISSUE THREAD

**Issue by aek** [zatosource/zato#878]
In Zato Zato Pub/Sub with AMPQ Channels and Endpoints doesn't let you configure an Exchange Type as defined at: 
https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges

So all the RabbitMQ AMPQ Exchanges will end up being the default direct exchange type preventing to be able to connect to an existing Exchange declared with a different Exchange Type

**Comment by zatosource** [comment]
Hello @aek - just to clarify it, you mean AMQP outgoing connections in pub/sub subscriptions, not AMQP channels?

If so, when you fill out the form to create a new subscription, there are two fields labelled **AMQP exchange and routing key**. Is that not what you would like to use?

**Comment by dsuch** [comment]
Hello @aek - just to clarify it, you mean AMQP outgoing connections in pub/sub subscriptions, not AMQP channels?

If so, when you fill out the form to create a new subscription, there are two fields labelled **AMQP exchange and routing key**. Is that not what you would like to use?

**Comment by aek** [comment]
Hi @dsuch 
No, the exchange type is something different. It only allow you to select and use one of the following values

Name | Default pre-declared names
-- | --
Direct exchange | (Empty string) and amq.direct
Fanout exchange | amq.fanout
Topic exchange | amq.topic
Headers exchange | amq.match (and amq.headers in RabbitMQ)


In my experience it will define the pattern of message delivery and routing over the exchange queues. The message routing will vary a lot based on the Exchange Type defined, also this will define the nature of the Exchange and RabbitMQ will not let you change/switch the Exchange type of the Exchange, so to change it you will need to create another Exchange or Delete the Exchange to be able to define it with a new Exchange Type. 

Direct Exchange Type is awesome but the others Exchange Types will let you design different behaviors and patterns of usage. 

This also could be a point of inconsistency between what exist in RabbitMQ and Zato.

**Comment by aek** [comment]
No, AFAIK there cannot be two or more exchanges with the same name but with different exchange type, there is a constraint for that in RabbitMQ. 

I have worked with pika instead of kombu but the thing rely on who declare the exchange, and where the exchange was declared and using what exchange type 
For example, here you can see how the exchange is declared using kombu and they are specifying the type as direct

https://medium.com/python-pandemonium/talking-to-rabbitmq-with-python-and-kombu-6cbee93b1298

Using 
```python
from kombu import Connection, Exchange, Producer, Queue

rabbit_url = “amqp://localhost:5672/”

conn = Connection(rabbit_url)

channel = conn.channel()

exchange = Exchange(“example-exchange”, type=”direct”)

producer = Producer(exchange=exchange, channel=channel, routing_key=”BOB”)

queue = Queue(name=”example-queue”, exchange=exchange, routing_key=”BOB”)
queue.maybe_bind(conn)
queue.declare()

producer.publish(“Hello there!”)
```

On Pika it's something similar but I have used the exchange declared on a channel of the Connection who will be the responsible of publishing the messages. 

I guess that boths libraries are very similar in features supported. That step of Exchange declaration is the one who will create an Exchange on the RabbitMQ backend if it doesn't exist so it will need to match the exchange type of already existing Exchanges or be able to check for that errors that you are seeing about the difference of exchange types between 2 exchanges with the same name.

As a summary Zato would need to check and validate that stuffs on Pub/Sub with AMPQ (RabbitMQ usage) to avoid painfull hidden errors for messages not reaching their respective Queues/Exchanges and also it would be good if the Exchange type could be configured in Zato because that it's an easy way to fix/match existing Exchanges and also to control the routing patterns of RabbitMQ allowing external applications to interoperate with Zato created AMPQ channels were the desired exchange type is not `direct`

**Comment by dsuch** [comment]
I understand your Pika code but this is not how Zato works like. We never declare exchanges like you do in your code.

The way I see it, you are worried that we declare exchanges by name before a message is published and since there is no way to specify an exchange type, it defaults to something that is not always the best choice.

But this is not the case. Zato simply sends messages to exchanges that are understood to have been already created upfront by AMQP admins, they are never declared in Zato.

I do not see how you managed to create a new exchange with pub/sub and an AMQP endpoint - can you tell me how to reproduce it?

**Comment by aek** [comment]
@dsuch that is not my kombu code, it's the code from the tutorial link on medium posted before to show you an example of how to declare the exchange type in kombu.
  
The way I see it is that exchange declaration is something that will happens no matter what, so Zato code it's doing it explicit or implicit using kombu and seems to be using the default direct exchange type.

I understand your point that it's not Zato role be who declare the exchange, and only use the created ones, but in order to be able to publish/send messages I think that the exchange declare step it's required. If you aren't declare it explicit it should be happening behind the scenes. In kombu there are defaults for exchange type='direct' all over the place.

To be able to reproduce a bad scenario you could just create a new exchange directly into RabbitMQ with an exchange type='fanout' for example and try to use it in Zato to send messages through that exchange.

**Comment by dsuch** [comment]
I still do not understand it fully and it looks we are talking about two separate matters in this ticket:

1. Unless I am misunderstanding what you are saying, it seems to me that you are saying that Zato, either directly or indirectly, can silently create exchanges and, while doing it, by default they will be of type 'direct'. I am unable to reproduce it, I have never seen it happen.

2. Again, unless I am not mistaken, you are saying that when you have an already existing exchange in RabbitMQ and that exchange is not of type 'direct' then it cannot be used from Zato. Again, I cannot reproduce it. I have just created an exchange of type 'headers', bound it to a queue, then I was able to send messages with the expected headers from Zato to that exchange and they arrived in the queue successfully.

I spent several hours on trying to reproduce it all and I am not able to. I will need step-by-step instructions on how to do it. Thank you.

**Comment by aek** [comment]
Looks that i was wrong then if you already test it and it works. I cannot test it right now, I will try to test it and share the results. All of my comments was based on my previous experiences using RabbitMQ as Message Broker.
Good to know that my concerns are not affected Zato

**Comment by dsuch** [comment]
I see, thanks. In that case, I will close the ticket but feel free to open a new one if you spot anything, but please include then concrete step-by-step details on how to reproduce it.
