### ISSUE TITLE
Enhance logging for SQL Notification

### ISSUE THREAD

**Issue by Energytechglobal** [zatosource/zato#882]
Within Zato 2.0 or Zato 3.0, currently, there is no way to track whether the SQL Notification is working or not. All other services in Zato will have some kind of logging when they run and we can verify the logs to check whether the service is running or not.

So can we introduce/enhance logging for SQL Notification, such that the SQL Notification service will log the details of its execution?

**Comment by dsuch** [comment]
Hello,

this is done - in Zato 3.1 there is a new logger in logging.conf called **zato_notif_sql** which by default logs information to stdout and a file called notif-sql.log.

The information it saves out is such as below. It is stored when the notifier is started and then each time it is executed. In DEBUG mode it will also store in logs any SQL rows found that are to be sent to the notifier's service.

```
INFO - Initializing notifier with config `{u'def_name': u'My SQL Connection', u'_encryption_needed': True, 'name': u'My Notification', 'notif_type': u'sql', u'service_name': u'helpers.raw-request-logger', 'interval': 1, 'is_active': True, 'def_id': 2, u'_encrypted_in_odb': True, 'query': u'SELECT id from service;', 'password': u'******', 'id': 1}`

INFO - SQL notifier running with config `{'config': {u'def_name': u'My SQL Connection', u'_encryption_needed': True, 'name': u'My Notification', 'notif_type': u'sql', u'service_name': u'helpers.raw-request-logger', 'interval': 1, 'is_active': True, 'def_id': 2, u'_encrypted_in_odb': True, 'query': u'SELECT id from service;', 'password': u'******', 'id': 1}}`

INFO - Executing `helpers.raw-request-logger` in background with 611 rows
```
