### ISSUE TITLE
Documentation for name of loadbalancer pidfile not correct

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#896]
In https://zato.io/docs/admin/guide/install-config/config-lb.html is stated that the pidfile for the load-balancer is configurable. However, due to GH #733, the name of the pidfile is now fixed ('pidfile', like for zato servers and web-admin).

**Comment by dsuch** [comment]
Hi @jjmurre,

unlike the other components, load-balancers have two PID files:

* For HAProxy itself
* For its command agent

The agent is a lightweight server running in front of HAProxy which accepts commands such as restart/stop/check config and forwards them to HAProxy. Otherwise, HAProxy itself would not be able to process any such remote requests. The agent is typically on port 20151.

It is this agent's PID file that can be configured through lb-agent.conf, the other one ('pidfile') is always the same for all components.

**Comment by jjmurre** [comment]
Ok. Then something else is the case. For Zato 2.0.8 instances, I see those two pidfiles. However, when I start zato 3 instances, there is only one pidfile (named 'pidfile'). The file 'zato-lb-agent.pid' is missing. And the PID in this pidfile is referring to the haproxy process.

In the code for `LoadBalancerAgent`, I see this reference to a pidfile:

` self.haproxy_pidfile = os.path.abspath(os.path.join(self.repo_dir, '../', '../', MISC.PIDFILE))`

Could it be that the fix in GH #733 inadvertantly took the wrong pidfile?

**Comment by jjmurre** [comment]
In the current zato3 version (support/3.0) the pidfile "zato-lb-agent.pid" is still missing. Will this be a permanent change, or is this a bug that will be fixed?

**Comment by dsuch** [comment]
Hi @jjmurre - this file should exist. Do ls and ps return different information in your environment?

```
[~/env/zato1/load-balancer]: ls 
config  haproxy-stat.sock  logs  pidfile  zato-lb-agent.pid
[~/env/zato1/load-balancer]:
```

```
[~/env/zato1/load-balancer]: ps -efl | grep zato.agent
0 S dsuch    24333  1544 10  80   0 - 135720 poll_s 16:53 pts/23  00:00:00 /home/dsuch/projects/zatosource-zato/code/bin/python -m zato.agent.load_balancer.main /home/dsuch/env/zato1/load-balancer/config/repo sync_internal=FalseZATO_ZATO_ZATOsecret_key=ZATO_ZATO_ZATOfg=False
[~/env/zato1/load-balancer]:
```

**Comment by jjmurre** [comment]
Hi @dsuch,

I see this:

```
  [app-batches-acc@SCL-VAC-OTA zato]$ cd load-balancer/
  [app-batches-acc@SCL-VAC-OTA load-balancer]$ ls
  config  haproxy-stat.sock  logs  pidfile
```

And:
```
0 S app-ser+ 22851 22378  0  80   0 - 175994 poll_s 2018 ?        00:07:34 /opt/APPS/servicebus/acc3/zato-servicebus/3.0/code/bin/python -m zato.agent.load_balancer.main /opt/APPS/servicebus/acc3/zato/load-balancer/config/repo sync_internal=FalseZATO_ZATO_ZATOsecret_key=ZATO_ZATO_ZATOfg=True
```

The git revision:
```
commit 61b30abec5acc43a07338779f41201bc8d20c4ef
Author: Dariusz Suchojad <dsuch-github@m.zato.io>
Date:   Fri Jan 4 10:47:15 2019 +0100

    GH #907 - Use the already obtained absolute path to the server.
```

**Comment by dsuch** [comment]
It looks that you started the load-balancer in foreground, is that not the case?

In this situation, yes, the embedded HAProxy instance creates file 'pidfile' (this is outside of our control) but the agent does not, seeing as it runs in foreground.

**Comment by jjmurre** [comment]
Yes, the loadbalancer (and other Zato processes) are controlled by supervisor. One of the requirements of supervisor is that the supervised processes are not daemonized, but are running in the foreground.

So, in that situation, the content of 'pidfile' is the haproxy process, and there is no pidfile for the Zato agent?

**Comment by jjmurre** [comment]
This is good new, because it make my supervisor config easier. Now I understand what the reason is that I can only see 'pidfile'. This issue can be closed.

**Comment by jjmurre** [comment]
The only problem is, that when supervisor stops the agent, the haproxy process keeps running, but that is something I have to take care of myself in the supervisor configuration I suppose.

**Comment by dsuch** [comment]
Not sure if this helps but certainly when you run ```zato start load-balancer --fg``` the agent then can be stopped with Ctrl-C and it takes HAProxy down with it, i.e. stopping the agent stops HAProxy too.

You can look it up in source, method stop_haproxy in ./code/zato-cli/zato/cli/stop.py, and then perhaps do the same under supervisord.

**Comment by jjmurre** [comment]
Would be nice if the loadbalancer agent process, when running in foreground, would also listen to a SIGTERM, and would kill haproxy on SIGTERM. 
But, I can handle this in the supervisor script, so no urgent need for that.

For the record:

In supervisor, when starting the lb agent, first check if there is still an active haproxy:
```
if [ -f path-to-loadbalancer-pidfile ] && pkill -F path-to-loadbalancer-pidfile; rm -f path-to-loadbalancer-pidfile; zato start load-balancer --fg
```

**Comment by dsuch** [comment]
> Would be nice if the loadbalancer agent process, when running in foreground, would also listen to a SIGTERM, and would kill haproxy on SIGTERM.

Hi @jjmurre,

when the load-balancer agent runs in foreground, stopping it with Ctrl-C stops HAProxy - do you mean to add SIGTERM in addition to it?

**Comment by jjmurre** [comment]
No, when loadbalancer is run under supervisor, a stop command from supervisor for the loadbalancer is not a Ctl-C, but supervisor sends a SIGTERM to that loadbalancer process. This stops the loadbalancer process , but does not stop the underlying haproxy process.

**Comment by dsuch** [comment]
Right, just one question - does it have to handle SIGTERM? I am asking just in case it turns out to be a challenge for any reason. Would it be possible for you to send another signal if required?
