### ISSUE TITLE
Workflow to develop services

### ISSUE THREAD

**Issue by emre** [zatosource/zato#898]
What's your workflow to develop services on Zato? Hot deploying via IDEs are great, but what do you do about code completion?

**Comment by emre** [comment]
created a virtualenv and installed zato packages inside it. auto-completion works with that way.

But I would love to hear some workflows from experienced zato users.

**Comment by emre** [comment]
Another question:

How can I debug the services I write? E.g: using ipdb.

**Comment by dsuch** [comment]
Questions of this kind, involving discussions or feedback from existing users, rather than boiling down to concrete tasks or ideas to implement, are better suited for the [forum](https://forum.zato.io/). I will close the ticket - feel free to re-post over there.

Thank you.
