### ISSUE TITLE
pubsub GD Queue too small with mysql

### ISSUE THREAD

**Issue by bip91** [zatosource/zato#909]
Hi, 

When using large message (>64 ko), pubsub is working fine in RAM, 
but messages are trunked with GD on mysql.

This is due to the type of pubsub_message.data field.
setting mediumtext (2^24) or longtext (2^32) instead of Text (2^16) removes current limit on mysql.

BR,
Bruno

**Comment by dsuch** [comment]
Hi @bip91,

you are right, this should be bigger, I will see about making it use LONGTEXT instead.

Regards.

**Comment by dsuch** [comment]
Thank you again @bip91 - this is done.

If you install the [latest updates](https://zato.io/docs/admin/guide/install/update.html) and create a new environment, the message's max_size will be now 2 GB.
