### ISSUE TITLE
item.last_interaction_time not always exists

### ISSUE THREAD

**Issue by bip91** [zatosource/zato#910]
https://github.com/zatosource/zato/blob/411b19c04137778d25d8233bf1315694249bbe7b/code/zato-server/src/zato/server/service/internal/pubsub/endpoint.py#L269

Attribute **last_interaction_time** on **item** does not not always exist,
In that case, Message cannot be displayed on web-admin.
 
A possible workaround is the following except block : 

>             #if item.last_interaction_time:
>             try:
>                 item.last_interaction_time = datetime_from_ms(item.last_interaction_time * 1000.0)
>             except AttributeError as e:
>                 pass

BR,

**Comment by dsuch** [comment]
Thanks again for spotting it - this is also done.
