### ISSUE TITLE
Implement aliases in cache

### ISSUE THREAD

**Issue by jsabater** [zatosource/zato#911]
As per the discussion on [this thread on the forum](https://forum.zato.io/t/cache-entries-with-multiple-keys-and-same-content/1846/), some model classes may have more than one unique id (e.g. the locator of a flight), so you may find yourself in the need to implement services to search by any of such ids. When caching the results via Zato's Cache API, allowing cache keys to have aliases may be a nice feature to have. One way to set a cache entry with aliases would be:

`self.cache.set('key', 'value', alias=['alias1', 'alias2'])`

Meaning there would be three pointers to the same data, which could be retrieved through any of the following calls:

```
self.cache.get('key')
self.cache.get('alias1')
self.cache.get('alias2')
```

The cache system would have to take into consideration dealing with aliases when something happens to the key, such as expiring, being deleted, being re-created or updated so that no ghost aliases are left behind.

Finally, when dealing with calls such as **get_by_prefix**, a **limit** parameter would come in handy, as it is expected that the developer knows the amount of alises, hence can _help_ the search by narrowing it down to a number of occurrences.

**Comment by dsuch** [comment]
The **limit** parameter is done, you can use it with any if get/set/delete/expire_by_* operation, e.g. 

```python
out = self.cache.default.get_by_prefix('my-prefix', limit=3)
```

Aliases are a bit more involved and will be added at a later time.
