### ISSUE TITLE
Add GraphQL Support

### ISSUE THREAD

**Issue by aek** [zatosource/zato#927]
Nowadays GraphQL offers many advantages over REST. It could be good to have GraphQL support with possibles usages like being able to orchestrate multiple Zato services calls in one request and also it could be a better way to express service data types than SimpleIO

**Comment by dsuch** [comment]
Hi @aek,

I was planning to investigate GraphQL at one point so it is nice that you suggested it too.

There is not enough time to do it before the 3.1 release in June but I am looking forward to it for sure.

**Comment by aek** [comment]
I know. It's a lot of work but could bring a lot of power features for automation and orchestration of services without the need of create a new ones.

**Comment by jpoa** [comment]
Would also be interested in this

**Comment by dsuch** [comment]
Hi @jpoa,

I have had a brief look at GrapQL but I do not have a specific vision yet.

Based on your experience, requirements and expectations - how would you see it working in Zato? What are you interested in, in particular and in general?

Thanks.

**Comment by dsuch** [comment]
Closing until the work starts.
