### ISSUE TITLE
Elasticsearch library is very old

### ISSUE THREAD

**Issue by crsde** [zatosource/zato#930]
Hello, i hit in problem when unable to index document  within Elasticsearch connection, because got an error, looks like:
`TransportError: TransportError(406, u'Content-Type header [] is not supported')
`
After some research i understood that included es library is very-very old - elasticsearch==0.4.5
and have this issue with actual es installations, while actual are 6.3.1.

**Comment by dsuch** [comment]
Thank you - it will be updated in Zato 3.1. In the meantime, you can install a newer version using pip that Zato ships with.

**Comment by dsuch** [comment]
Already done - closing the ticket.
