### ISSUE TITLE
Web UI: REST channel method gets overwritten to "---", service throws 504 

### ISSUE THREAD

**Issue by klamar** [zatosource/zato#936]
How to reproduce:
* Create a new REST channel, keep the method field empty: ![image](https://user-images.githubusercontent.com/1537125/55559117-d4dcf880-56ed-11e9-9392-5ff078beb2a6.png)
* reload the page (F5)
* service is now displayed in table with method "---" which is basically a correct representation of an empty or not-set method
* click on edit
* method field now contains string "---" 
![image](https://user-images.githubusercontent.com/1537125/55559245-153c7680-56ee-11e9-8acb-6cb2a94a13e5.png)
* when clicking on the "OK" button zato will save the "---" value to DB
* when executing the service it will return now a 504 because the request method (e.g. "GET") does not match "---"

**Comment by dsuch** [comment]
Hi @klamar,

just to confirm it - this appears to be Zato 3.0 rather than 3.1 built from source?

**Comment by klamar** [comment]
I am running:

```
$ zato --version
Zato 3.0.0+rev.f5dbf26b
```

Which is the latest version I can get using the install instructions from https://zato.io/docs/admin/guide/install/ubuntu.html

This is how I installed it on ubuntu 18.04:

```
curl -s https://zato.io/repo/zato-0CBD7F72.pgp.asc | sudo apt-key add - \
    && sudo apt-add-repository https://zato.io/repo/stable/3.0/ubuntu \
    && sudo apt-get install -y zato

```

**Comment by dsuch** [comment]
Thanks, this is done - can you install latest updates and try again?

https://zato.io/docs/admin/guide/install/update.html

**Comment by klamar** [comment]
Works like a charm 👍
