### ISSUE TITLE
Multiple Users in the channel definition

### ISSUE THREAD

**Issue by aek** [zatosource/zato#96]
Currently there is no way of way of specify more than one user per channel
If you have an app and it has 3 modules each of which wants to invoke a Zato service. In that case it would be indeed desirable to be able to specify a list of security definitions attached to a channel but it's not possible currently - these need to be separate channels instead of using one of the existing. This involve the possibility to get the current user that is executing the service

**Comment by dsuch** [comment]
Will be working on it for 2.1. Thanks @aek.
