### ISSUE TITLE
Stuck docker run

### ISSUE THREAD

**Issue by FurkanSalih** [zatosource/zato#961]
Hello everyone, 

Currently, I encountered problem when quick installing with docker. I'm following this documentation.

https://zato.io/docs/admin/guide/install/py3/docker.html (Zato 3.1.0)

1) Downloaded Zato Docker image

2) Ran docker image
```
sudo docker run -it --rm -p 22 -p 6379:6379 -p 8183:8183 -p 17010:17010 -p 17011:17011 -p 11223:11223 --name zato registry.gitlab.com/zatosource/docker-registry/quickstart:3.1-py3
```

In this step, following logs are printed. But it stuck at last step.  
```
...
server started
CREATE DATABASE
2019/06/19 08:45:23 Ready: tcp://localhost:5432.
Running quickstart-bootstrap
2019-06-19 08:45:23.394 UTC [67] LOG:  incomplete startup packet
+ /opt/zato/current/bin/zato quickstart create --odb_host localhost --odb_port 5432 --odb_user postgres --odb_db_name zato --odb_password 40a71f25-c2d6-4b36-a9e5-e73f701153d3 --kvdb_password '' /opt/zato/env/qs-1/ postgresql localhost 6379
```

Waited 10 minutes. Ran again multiple times but it didn't go well. I figured out something when interrupted process.

```
+ /opt/zato/current/bin/zato quickstart create --odb_host localhost --odb_port 5432 --odb_user postgres --odb_db_name zato --odb_password 40a71f25-c2d6-4b36-a9e5-e73f701153d3 --kvdb_password '' /opt/zato/env/qs-1/ postgresql localhost 6379

^CTraceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 415, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 377, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 458, in __init__
    self.stdin_data = read_stdin_data()
  File "/opt/zato/3.1.0/code/zato-common/src/zato/common/util/cli.py", line 26, in read_stdin_data
    data = to_read[0].read()
KeyboardInterrupt
```

Process is waiting some input from stdin and I think it can't get anything from it. I don't know why it needs to listen stdin in this point. I find some workaround to keep going but it is not best. 

Pressing Control+d to send EOF to stdin can solve this problem

I tried another tutorial for zato 3.0 (https://zato.io/docs/3.0/admin/guide/install/docker.html). Same thing happened in here too.

I hope you can help me in this issue.

Zato versions: 3.0.0 and 3.1.0
OS version: macOs High Sierra 10.13.6
Docker version: 2.0.0.3

**Comment by DimShadoWWW** [comment]
Hello, @FurkanSalih 
can you run ```docker exec -it zato /bin/bash``` (in another terminal) after 10 seconds of the ```docker run ..``` and see whats processes are running?
I just ran the same command as you and it worked for me.

**Comment by FurkanSalih** [comment]
![Screen Shot 2019-06-20 at 09 33 16](https://user-images.githubusercontent.com/8011741/59826254-9cd57100-933e-11e9-896f-a4c355faaee5.png)

**Comment by DimShadoWWW** [comment]
Thank you, @FurkanSalih . Can you try again and post the output of
```
ps -edaf
```

**Comment by dsuch** [comment]
Hello @FurkanSalih,

will it be, please, possible for you to work with @DimShadoWWW on this question? I would very much like to find an answer to it as well.

Thank you.

**Comment by FurkanSalih** [comment]
@DimShadoWWW, @dsuch sorry for late response,

`ps -edaf` output as following 

```shell
root@02d6a29f7b9e:/opt/zato/3.0/code# ps -edaf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 11:11 pts/0    00:00:00 /bin/bash /entrypoint.sh
postgres    42     1  0 11:11 ?        00:00:00 /usr/lib/postgresql/10/bin/postgres -D /var/lib/postgresql/data -c listen_addresses=127.0.0.1
postgres    44    42  0 11:11 ?        00:00:00 postgres: checkpointer process
postgres    45    42  0 11:11 ?        00:00:00 postgres: writer process
postgres    46    42  0 11:11 ?        00:00:00 postgres: wal writer process
postgres    47    42  0 11:11 ?        00:00:00 postgres: autovacuum launcher process
postgres    48    42  0 11:11 ?        00:00:00 postgres: stats collector process
postgres    49    42  0 11:11 ?        00:00:00 postgres: bgworker: logical replication launcher
root        65     1  0 11:11 pts/0    00:00:00 sudo -H -u zato /opt/zato/quickstart-bootstrap.sh
zato        66    65  0 11:11 pts/0    00:00:00 /bin/bash /opt/zato/quickstart-bootstrap.sh
zato        67    66  2 11:11 pts/0    00:00:02 /opt/zato/3.0/code/bin/python2.7 /opt/zato/current/bin/zato quickstart create --odb_host localhost --odb
root        75     0  4 11:12 pts/1    00:00:00 /bin/bash
root        90    75  0 11:12 pts/1    00:00:00 ps -edaf
```

**Comment by dsuch** [comment]
Hello @FurkanSalih - do you have both /opt/zato/3.1.0 and /opt/zato/3.0 directories in that container?

**Comment by FurkanSalih** [comment]
@dsuch No, only `/opt/zato/3.0` folder is exist.

**Comment by dsuch** [comment]
Hm, I am not sure in that case - do I understand it correctly that you installed Zato 3.1 and it created /opt/zato/3.0 in the container?

I am just trying to pinpoint the issue so this is why I ask about all the details.

**Comment by dsuch** [comment]
Hello @FurkanSalih - I think I have found a solution to it. After you create a new container / pull updates, this should be resolved.

However, I would still like to understand why you initially had /opt/zato/3.1.0 and then it was /opt/zato/3.0.

Thanks.

**Comment by FurkanSalih** [comment]
@dsuch, We encountered some problem in 3.1 container. So I switched back to 3.0 dockerfile. It is normal to see /opt/zato/3.0 because as I said I find 3.0 dockerfile and build it.

**Comment by dsuch** [comment]
I see - in that case, can you check it under 3.1 again? Thank you.

**Comment by FurkanSalih** [comment]
Hello @dsuch, I tested and couldn't counter any problem. Thanks for your support

**Comment by dsuch** [comment]
Thank you for opening the ticket @FurkanSalih and I appreciate your assistance in resolving it!
