### ISSUE TITLE
Type errors for 'zato create server' command 'secret_key' and 'jwt_secret' arguments 

### ISSUE THREAD

**Issue by SharpThunder** [zatosource/zato#963]
Hello everyone.

After a succesfull zato 3.1 installation on Ubuntu 16.04, when I try to create a new server using 
https://zato.io/docs/admin/guide/install-config/install-server.html guide, I faced with errors.

```
zato create server /opt/zato/server1 postgresql 10.0.2.10 6379 cluster server1  --odb_host 10.0.2.10 --odb_port 5432 --odb_user zatouser --odb_db_name zatodb --postgresql_schema zatoschema --odb_password 1
```
```
File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/create_server.py", line 705, in execute
    key1 = args.secret_key or Fernet.generate_key()
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/cryptography/fernet.py", line 51, in encrypt
    return self._encrypt_from_parts(data, current_time, iv)
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/cryptography/fernet.py", line 55, in _encrypt_from_parts
    raise TypeError("data must be bytes.")
TypeError: data must be bytes.
```

This error happens because even if there is no 'jwt_secret' argument, 'jwt_secret'  argument passed on Fernet as None. Also when trying to pass a 'jwt_secret' argument, argparser parses argument as a string type. This also gives same output.

For 'secret_key' argument, None value, bypassed by
``` 
key1 = args.secret_key or Fernet.generate_key()
```
however argparser parses argument as a string type.

To fix this i edited to code to encode as byte and check None value, and opened a pull request.
Changed lines are below. 

https://github.com/zatosource/zato/pull/962

```
key1 = getattr(args, 'secret_key', None)
 if key1:
                key1 = str.encode(key1)
            else:
                key1 = Fernet.generate_key()

```
```
jwt_secret = getattr(args, 'jwt_secret', None)
            if jwt_secret:
                jwt_secret = str.encode(jwt_secret)
            else:
                jwt_secret = Fernet.generate_key()
            zato_misc_jwt_secret = fernet1.encrypt(jwt_secret)
```
Thanks.

**Comment by DimShadoWWW** [comment]
Hello, @SharpThunder . Can you update Zato using this [guide](https://zato.io/docs/admin/guide/install/update.html) and check if it works for you? Thank you

**Comment by SharpThunder** [comment]
Hello, I returned to v3.0 but i decided to setup quickstart cluster and test if it is works. However quickstart 
```
[1/9] Certificate authority created
[2/9] ODB schema created
[3/9] ODB initial data created
Could not create the server, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/create_server.py", line 732, in execute
    zato_misc_jwt_secret = fernet1.encrypt(getattr(args, 'jwt_secret', Fernet.generate_key()).encode('utf-8'))
AttributeError: 'bytes' object has no attribute 'encode'
`
[4/9] server1 created
Could not create the server, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/create_server.py", line 732, in execute
    zato_misc_jwt_secret = fernet1.encrypt(getattr(args, 'jwt_secret', Fernet.generate_key()).encode('utf-8'))
AttributeError: 'bytes' object has no attribute 'encode'
`
[5/9] server2 created
[6/9] Load-balancer created
Superuser created successfully.
[7/9] Web admin created
[8/9] Scheduler created
[9/9] Management scripts created

```
gives " AttributeError: 'bytes' object has no attribute 'encode' " error.

**Comment by dsuch** [comment]
Are you running the latest updates @SharpThunder ?

https://zato.io/docs/admin/guide/install/update.html

**Comment by SharpThunder** [comment]
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 17 (delta 9), reused 17 (delta 9), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/zatosource/zato
   0239c6f..4cb3d63  main       -> origin/main
Already up-to-date.

I set it up on last friday, I did try to update it, however It's already up-to-date.
Thanks

**Comment by dsuch** [comment]
I can see that you pull updates from branch 'main' - can you tell me how you installed Zato? By following what instructions?

**Comment by SharpThunder** [comment]
I used instructions in this page. https://zato.io/docs/admin/guide/install/py3/ubuntu.html 

Here is my bash history 

 1  apt update && apt upgrade
    2  ip a
    3  reboot now
    4  apt-get install python-software-properties
    5  curl -s https://zato.io/repo/zato-3.1-C9B13DF28CFE287D.pgp.txt | sudo apt-key add -
    6  add-apt-repository    "deb [arch=amd64] https://zato.io/repo/stable/3.1/py3/ubuntu $(lsb_release -cs) main"
    7  apt update && apt-get install zato -y
    8  su - zato
    9  history
   10  su - zato
   11  apt-get install redis-server
   12  sudo systemctl enable redis-server.service
   13  nano /etc/redis/redis.conf
   14  systemctl start redis
   15  su zato
   16  history

Thanks.

**Comment by dsuch** [comment]
Thank you for the comprehensive answer, I appreciate it.

I just have one more request, which you in a way already answered but I would like to see the explicit output of these commands. Thanks again.

```
cd /opt/zato/current
git log -1
```

**Comment by SharpThunder** [comment]
```
commit 917ce0435c742b5c6b778ae3a0209ca7eefc46c9
Merge: f181ab9 a6820be
Author: Anielkis Herrera <aherrera@zato.io>
Date:   Fri Jun 21 06:01:48 2019 -0500

    Merge branch 'anielkis-b-gh963-type-errors' into support/3.1
```
Here is the output

**Comment by dsuch** [comment]
Hello @SharpThunder - I found the root cause, can you please install the updates and try it now? Thanks.

https://zato.io/docs/admin/guide/install/update.html

**Comment by SharpThunder** [comment]
I did not tried with "create server" but quick start works and your change in the code should fix create server too.

**Comment by dsuch** [comment]
Great, it is good to hear it - I will close the ticket in that case, if you need anything, feel free to create a new one. Thank you again.
