### ISSUE TITLE
subcription javascript error on fresh install dockerized 3.1

### ISSUE THREAD

**Issue by LordShion** [zatosource/zato#964]
Hi on a fresh zato 3.1 dockerized instance, we're facing an error on javacript on clicking over create subscription link

Traceback (most recent call last):
KeyError: 'zato_dyn_form_default' brython.js:7415:9

We suspect a library version problem
Could we solve this problem on downgrading brython library (we'll try that today).

best regards

**Comment by dsuch** [comment]
Hello @LordShion,

I cannot reproduce it on latest Firefox and Chrome - can you tell me what your browser and Zato versions are?

$ zato --version
Zato 3.1+rev.c34a7c3f3-py2.7.15
$

**Comment by LordShion** [comment]
Zato 3.1+rev.544100e-py3.6.8

built with docker folder

**Comment by dsuch** [comment]
I cannot reproduce it under any conditions - please post the version of your browser and step by step instructions how to reproduce it, what address it is happening under and what exactly is the text of the link that you click. Thanks.

**Comment by LordShion** [comment]
Tryied also, with zato docker image from this page
[https://zato.io/docs/admin/guide/install/py3/docker.html]
chrome and firefox same thing  
chrome: Version 73.0.3683.86 (Build officiel) (64 bits)
firefox: 67.0.4 (64-bit)  firefox for arch linux
follow stop on page
click on create subcription
chrome: 
`Traceback (most recent call last):
KeyError: 'zato_dyn_form_default'
brython.js:7416 Uncaught Error
    at Object._b_.KeyError.$factory (eval at $make_exc (brython.js:6771), <anonymous>:12:363)
    at Object.JSObject.__getitem__ (brython.js:7383)
    at brython.js:7368
    at Object.$B.$getitem (brython.js:5291)
    at __init__0 (eval at $B.loop (brython.js:4631), <anonymous>:40:130)
    at type.__call__ (brython.js:4992)
    at factory (brython.js:5059)
    at zato_run_dyn_form_handler17 (eval at $B.loop (brython.js:4631), <anonymous>:756:116)
    at self.js.(:8183/zato/pubsub/subscription/anonymous function) (http://localhost:8183/static/brython/dist/brython.js:7410:18)
    at Function.$.fn.zato.pubsub.subscription.create (subscription.js:256)`

firefox:
`Traceback (most recent call last):
KeyError: 'zato_dyn_form_default' brython.js:7415:9
Error: brython.js line 6771 > eval:12:363
    $factory http://localhost:8183/static/brython/dist/brython.js line 6771 > eval:12
    __getitem__ http://localhost:8183/static/brython/dist/brython.js:7383
    __getattribute__ http://localhost:8183/static/brython/dist/brython.js:7368
    $getitem http://localhost:8183/static/brython/dist/brython.js:5291
    __init__0 http://localhost:8183/static/brython/dist/brython.js line 4631 > eval:40
    __call__ http://localhost:8183/static/brython/dist/brython.js:4992
    factory http://localhost:8183/static/brython/dist/brython.js:5059
    zato_run_dyn_form_handler17 http://localhost:8183/static/brython/dist/brython.js line 4631 > eval:756
    attr http://localhost:8183/static/brython/dist/brython.js:7410
    create http://localhost:8183/static/js/pubsub/subscription.js:256
    <anonymous> javascript:$.fn.zato.pubsub.subscription.create():1

`

**Comment by kkarolis** [comment]
Can only confirm we are experiencing this as well

**Comment by dsuch** [comment]
Thanks @kkarolis,

I had never been able to reproduce this situation myself but after your message I tried it once again and suddenly, yes, I can see this exception:

```
Traceback (most recent call last):
KeyError: 'zato_dyn_form_default'
```

I am not sure what changed in the meantime, certainly nothing in Zato seeing as I was not able to replicate it, and it probably was a new browser version.

At any rate, I will be able to look into it when I have enough time.

**Comment by kkarolis** [comment]
Managed to pin down the problem a bit. Browsers tested:
`Firefox Dev Edition 68.0b9`
`Chromium Version 75.0.3770.80 (Official Build) Arch Linux (64-bit)`

Problem appears with docker zato `py3` quickstart:
**image**: `registry.gitlab.com/zatosource/docker-registry/quickstart   3.1-py3                3ee72a3a302d`
**zato version**: `Zato 3.1+rev.50e2f7b-py3.6.8`

But is not apparent with the `py27` image:
**image**: `registry.gitlab.com/zatosource/docker-registry/quickstart   3.1-py27               cb4d5b9d924e`
**zato version**: `Zato 3.1+rev.50e2f7b-py2.7.15`

**Comment by crsde** [comment]
Hit into the same issue. in Chrome  74.0.3729.169, FF 67.0, both affected.
Using 3.1-py3 in Kubernetes.

**Comment by bip91** [comment]
It seems to be a unicode error issue.
In code/zato-web-admin/src/zato/admin/web/views/pubsub/subscription.py
in line 74 :
#targets.append({b'id':item.id, b'name':item.endpoint_name.encode('utf8')})
targets.append({'id': item.id, 'name': item.endpoint_name})

This works for me.

**Comment by crsde** [comment]
@bip91 sadly. not working for me. And i not understand how these variables arrives to client but window.zato_select_data_target == null in my case
