### ISSUE TITLE
Outgoing Rest , no http accecpt header

### ISSUE THREAD

**Issue by rileylu** [zatosource/zato#965]
failed to create with error: KeyError: 'http_accept'

**Comment by FurkanSalih** [comment]
I encountered same problem. I will create pull request for this.

**Comment by dsuch** [comment]
Thank you @FurkanSalih - I merged the PR.

@rileylu - please install the latest updates as documented here and the fix will be included:

https://zato.io/docs/admin/guide/install/update.html

**Comment by rileylu** [comment]
fixed.Thanks a lot
