### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by itmicus** [zatosource/zato#971]
Hello.
Can I run PowerShell scripts from Zato?

**Comment by dsuch** [comment]
Hello,

I have never tried it - can you tell me what is required to run them? How would you run them outside Zato?

Regards.

**Comment by itmicus** [comment]
For example, Hard Enterprise, many systems based on Microsoft products (AD, Exchange, Skype, MSSQL, etc)  I have workflow to manage it all. This workflow it is .ps1 script, that I run with some arguments.
I want use Zato to run this .ps1 script with arguments from other system.

**Comment by dsuch** [comment]
This is understood but how do you run them?

I do not know much about Windows and I do not know what the options to execute PowerShell scripts are given that Zato is a Linux-based platform that would run on its own servers, independent of any Windows systems.

**Comment by itmicus** [comment]
I think I know what you need.
https://github.com/diyan/pywinrm
This module can help, becuase this module also using Ansbile to run PowerShell from tasks.
It will be awesome if you create post in your blog, how can we use Zato and pywinrm to run some of scripts on Windows based machines.

**Comment by dsuch** [comment]
Thanks, this is a useful idea - I will think about it in upcoming days, though I cannot say if it can be this week already. I will keep this ticket updated with details as soon as they emerge.

**Comment by itmicus** [comment]
and it will be usefull if you add this features to docker images ;)

**Comment by dsuch** [comment]
Here is the blog post - extending it and making it all part of Zato core is a good idea but this will not be done right now. I will update this ticket once it is implemented.

https://zato.io/blog/posts/windows-command-powershell-api.html

**Comment by dsuch** [comment]
Closing old tickets.
