### ISSUE TITLE
AttributeError: 'StrictRedis' object has no attribute 'xadd'

### ISSUE THREAD

**Issue by henyhollar** [zatosource/zato#983]
Hello all and thumbs up for the good work on Zato.

I am trying to use redis stream on zato but i got this error: AttributeError: 'StrictRedis' object has no attribute 'xadd'.
I am using zato from the docker. How do i get this to work?

Thanks

**Comment by dsuch** [comment]
Hello @henyhollar,

it is nice to hear from you but I am not fully sure - why are you asking a Redis question in this tracker?

Regards.

**Comment by dsuch** [comment]
Closing due to the lack of activity.
