### ISSUE TITLE
LDAP Outgoing connection

### ISSUE THREAD

**Issue by littlechicks** [zatosource/zato#984]
Hello, 

I am new to Zato, and wanted to create an outgoing connection for fetching my LDAP Server (Windows server 2016). I created a cluster with the quickstart commands.

I configured the connection like below
![image](https://user-images.githubusercontent.com/54933792/64324178-2273cf00-cfc6-11e9-8b3b-f77755dd2925.png)

Then I putted the password by "Changing Password".

And when I try the run a ping, I get an error on my browser.

![image](https://user-images.githubusercontent.com/54933792/64324304-68c92e00-cfc6-11e9-82e4-87f142729c86.png)

Any idea of this error ? 

Thanks !

**Comment by littlechicks** [comment]
And in the admin.log I just have this line when I run the ping :
`2019-09-05 01:45:51,362 - INFO - 3095:DummyThread-61 - zato_admin:0 - Request; service:`zato.generic.connection.ping`, data:`{'id': 1}` cid:`c018021617b65cbec7f69772`, `

**Comment by dsuch** [comment]
Hello @littlechicks,

thank you for the ticket.

It looks that this exception possibly indicates that connection parameters are not correct - could you please double-check that they are as expected, including its password? Are you able to ping the connection when you set a new password?

Regards.

**Comment by littlechicks** [comment]
Thanks ! I resolved my issue :)

**Comment by dsuch** [comment]
It is good to hear that it is resolved but I would like to hear how you achieved it? Thank you.

**Comment by littlechicks** [comment]
It was just my network not well configured.
The LDAP server was not in my subnet, so I've to add some static routes for fetching the LDAP server.

Thanks !
