### ISSUE TITLE
ZATO 3.1 - PubSub Notify issue

### ISSUE THREAD

**Issue by bip91** [zatosource/zato#998]
**Context :** 
- Zato environment : 
```
$ zato --version
Zato 3.1+rev.770617e-py3.6.8
$ git log
commit 770617e (HEAD -> support/3.1, origin/support/3.1)
```

**What happen**
Pubsub Notify can be defined but a **too many values to unpack** error is raised when a message is published.

**How to reproduce**
- Define a  new notify pubsub subscription with a service (ie service_XXX)
- On publishing messages, Zato raises the error below due to a bad data_format on outgoing connection (try to unpack a Json doc (message list))
```
 ...
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)
```

if Channel form have a data_format field, we do not have anymore the data_format field in outgoing rest connection is version 3.1, so data format cannot be set : 

![image](https://user-images.githubusercontent.com/2768409/68493390-b1ae9480-024c-11ea-9f70-d24d28f8453c.png)

**Workaround** 
set data_format on service directly in database  :
```
update http_soap set data_format='json' where name = ‘service_XXX’ ;
```

**Comment by dsuch** [comment]
Hello @bip91,

thank you for the ticket but I do not fully understand how to reproduce it.

* Can you tell me what you mean by defining a new pub/sub notification with a service?
* What is the full traceback?
* How is the attached screenshot related to everything?

**Comment by bip91** [comment]
Ok, I understand. 
I will try to explain this more clearly.

To reproduce the error :
- Build an outgoing connection _(test2.outcon in this example)_
  _(for the test, outgoing connection is connected to a channel  with a log service on URL /test/test3)_
- Define any topic with a **subscription  in notify mode** with REST outconn link to outgoing connection
  
![image](https://user-images.githubusercontent.com/2768409/68499927-c5f98e00-025a-11ea-85a4-a3d80806565e.png)
- Publish a message on topic

Full traceback :
```
2019-11-07 15:28:29,853 - ESC[1;33mWARNINGESC[0m - 8335:DummyThread-25 - zato.server.service:0 - Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 538, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 86, in handle
    func(self, msg, subscription, endpoint_impl_getter)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 117, in _deliver_rest_soap
    http_soap.conn.http_request(subscription.config.out_http_method, self.cid, data=data)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 367, in http_request
    response = self.invoke_http(cid, method, address, data, headers, {}, params=qs_params, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 100, in invoke_http
    cert=cert, verify=verify, timeout=self.config['timeout'], *args, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 510, in prepare_body
    body = self._encode_params(data)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 97, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)
```

After analysis, it come from **data_format in outgoing connection** that is set to null instead of JSON.

Issue is that we cannot set this parameter on the outgoing connection screen (previously joined).
(This parameter has disapeared for some time now in 3.1 version).

After adjusting this field in ODB  
```
update http_soap set data_format='json' where name = ‘test2.outcon’ ;
``` 
and restarting server1. That's all ! 

Connection screen in 3.0 (below) has this parameter. 
Right fix is probably to add this data_format field again in 3.1 web-admin 
![image](https://user-images.githubusercontent.com/2768409/68501737-24c10680-025f-11ea-9faa-34ac883b1545.png)

(I will replace this traceback coming from a not yet updated git in a few hours when I will be on my test pc on which tests have been done. Only line numbers will change but it will more accurate)

**Comment by bip91** [comment]
When debuggin static/js/common.js at line 641 : 
![image](https://user-images.githubusercontent.com/2768409/71515335-0b255e00-28a3-11ea-96e0-4c16b943f8de.png)
![image](https://user-images.githubusercontent.com/2768409/71515442-7bcc7a80-28a3-11ea-8e7b-8971e61b2241.png)

**Comment by bip91** [comment]
@dsuch : Solving issue 943, will also solve this one. 2 different consequences of the same problem.

**Comment by dsuch** [comment]
Hello,

this was done under ticket #943 - many thanks for bringing it forth and finding the solution.
